### ISSUE TITLE
Content from Button pop-up is not replicated

### ISSUE THREAD

**Issue by boweden** [gildas-lormeau/SingleFile#105]
The problem:
Clicking on a button that would normally pop-up to show text results in no action.  

To reproduce:
Click on any of the 'Spoiler' buttons on this site -- http://www.sierrahelp.com/Hints/FatesOfTwinionSpoilers.html

Expected behavior:
It should display the content associated with that button (in the above example, the 'spoiler' relevant to that button)

Environment:
Win 7 64-bit, Opera

**Comment by gildas-lormeau** [comment]
To fix your issue, please uncheck the following options:
 - HTML content > remove hidden elements
 - Stylesheets > remove unused styles
 - Other resources > remove scripts

**Comment by boweden** [comment]
Thank you! Modifying those options seems to fix the problem.

I suppose my follow-up question now is, in what situations would I need to have those options (either all three or one or two of them) enabled? Is it possible to default to those "optimal" settings depending on the web page layout?

**Comment by gildas-lormeau** [comment]
I don't think choosing the best options automatically is something that is doable. However, your issue makes me think about implementing something like profiles. A profile would be a set of predefined options, there would be default profiles like "Fast save", "Faithful save", "Small page" and you could define your owns too. It would appear in the settings at the top right of the page with a combo box, and would be accessible from the context menu. You could also choose the profile you would like to associate with the default save (e.g. when clicking the button). What do you think about this?

**Comment by boweden** [comment]
That sounds wonderful. Especially the part about having a 'custom' option to choose your own settings for a specific web page, as well as having the ability to choose your own default profile.  Thank you again.

**Comment by gildas-lormeau** [comment]
Well, I did not really talk about a 'custom' option to choose your own settings for a specific web page... But I note it :p.

**Comment by gildas-lormeau** [comment]
The custom options associated to a URL is implemented in 1.9.7 (cf 'auto-settings rules' in the options page).

**Comment by boweden** [comment]
Wow, incredible. It goes much beyond than fulfilling my needs. :)  The way you implemented is very elegant and intuitive.  I honestly didn't expect the auto-save part to be so detailed and thorough. :+1:   Thank you.

**Comment by gildas-lormeau** [comment]
Thank you also very much for the feedback. I think the combination of features offers indeed some interesting possibilities :)

**Comment by endeavorz** [comment]
> To fix your issue, please uncheck the following options:
> 
>     * HTML content > remove hidden elements
> 
>     * Stylesheets > remove unused styles
> 
>     * Other resources > remove scripts

I had just installed Firefox recently after having used IE for ages, and always saved webpages in .mht, and of course IE did pick up things within Spoiler tags, and I was so disappointed that Firefox did not, until today upon searching the internet and found this SingleFile application, and then your post explaining how to Firefox now get Spoiler content too!

Nice Job Gildas Lormeau! Thank you so much!

**Comment by endeavorz** [comment]
Hello Gildas,

Yes I understand your very good points.

I have already ran into that situation, where with those 3 unchecked, it saves stuff behind spoilers yes and I can access it offline without internet, but, then on another website I see that website saves but, I can't view if offline now unless I let it connect... ahh, it's complicated I bet and that's no doubt why you did it the way you did with all these options.

I suppose I will have to use the what you said in your post before which is:

> The custom options associated to a URL is implemented in 1.9.7 (cf 'auto-settings rules' in the options page)
> 

I have not tried it yet though since I see I only have v1.9.2.....i just checked and made it v1.9.29
hmmm, maybe you did not release 1.9.7 yet?

Anyway I've got nearly everything unchecked on it so I may have to go back and re-checkmark things when I get a chance, to see if I can get it back. 

> The default options offer a guarantee the page will be saved properly and viewable without any internet access. They're also chosen to produce the smallest possible file.
> 

Understood, nice. However for my own use personally I don't care about the file size or compression options, it's more important (to me anyway) to have a 'complete duplicate' and have it display 'without' internet access. Other peoples needs ymmv of course. 

Anyway, in the meantime IE save as .mht still works for me no matter what on that site, so I just now opened IE and saved as an .mht to have it in the meantime.  

I guess I can leave IE installed and use it at the same time Firefox..

Thank you again.. nice stuff, I just need more time to figure out your settings I guess

**Comment by gildas-lormeau** [comment]
Hi @endeavorz,

You should be able to configure your own auto-settings rules via the options page > auto-settings rules. Note that version 1.9.7 is older than 1.9.29 (i.e. I increment the whole last number when releasing a new version).

**Comment by endeavorz** [comment]
1.9.7 is older than 1.9.29?  
...whole last number?
...I guess I see what you mean, but would of never caught that and I just use basic numbering where 1.9.7 is greater than 1.9.2. That must be a developer thing to do that I guess. 

----

Okay so I just tried to set up my auto settings and rules with a website that uses spoilers, but honestly I can't figure out the logic in how you have it set up and what to do.
I am sure it just be me though, and it's like that number thing.
Also I don't want to have it checkmarked to autosave webpages all the time, unless I manually click to save it - but maybe here too, your intent is different than my logical thought.

You have created a nice little extension though and so thank you. 

I got frustrated with it and just clicked the RESET button for now, and will use IE to save my webpage.
I think I like IE better than Firefox anyway, but again I guess I have no choice going forward :(

PS,
One thing I noticed with SingleFile set default, that I can save an email page (if I wanted to) in my yahoo account with your app, that's nice, because I could never do that with IE .mht and instead had to take a screenshot, which was fine.
So you see there is advantage with your SingleFile app to be gained, I just need to understand how to use it better i guess in those areas mentioned.
 
Thank you
