### ISSUE TITLE
pass "Referer" doesn't work in Firefox?

### ISSUE THREAD

**Issue by Landius** [gildas-lormeau/SingleFile#1056]
**Describe the bug**
with the option `Network > pass "Referer"` checked, and the first request returns 404,
the second request still send without `Referer` header.

**To Reproduce**
1. open `https://example.org`.
2. open devtool and insert `<img src="https://example.com/404.jpg">` to body html.
3. open extension devtool console, run `browser.webRequest.onSendHeaders.addListener(console.log, {urls: ['<all_urls>']}, ['requestHeaders'])`.
4. save the example.org page with Singlefile.
5. check the console output, there are two request details about `https://example.com/404.jpg`, but neither of them has "Referer" header.

**Expected behavior**
send retry request with "Referer" header.

**Screenshots**
![pic](https://user-images.githubusercontent.com/11910028/202655105-4bcd9baf-f42e-4366-bfaa-a6d38c1dca72.png)

**Environment**
 - OS: Windows 10
 - Browser: firefox 106
 - Version: 1.21.26

**Comment by gildas-lormeau** [comment]
I confirm the issue you described. Actually, the option works in Chrome but not Firefox because, within a content script, `fetch` does not trigger a "CORS error" when trying to retrieve `404.jpg` whereas the error is triggered in Chrome. I tried to pass the option `mode: "no-cors"` but Firefox seems to ignore it. This needs some investigation...

**Comment by gildas-lormeau** [comment]
I was able to circumvent the issue. The fix will ab available in the next version. Thank you!
