### ISSUE TITLE
Adding 'self' to default 'script-src' CSP directive

### ISSUE THREAD

**Issue by bryanph** [gildas-lormeau/SingleFile#1090]
**Is your feature request related to a problem? Please describe.**
The default CSP meta tag does not allow reading scripts from the same 'self' domain. I currently have a use case where this is desirable (I wish to inject some javascript into the output of a file generated by SingleFile and host it somewhere). 

Is there any security reasons for not including 'self' in the 'script-src' directive for the default CSP directive?

Adding a separate CSP response header doesn't work because "Adding additional policies can only further restrict the capabilities of the protected resource."

**Describe the solution you'd like**
Adding the 'self' rule to the 'script-src' directive

(happy to submit a pr)

**Comment by gildas-lormeau** [comment]
Indeed, I decided to use the strictest CSP possible mainly because that's the whole point of this feature. By default SingleFile saves the pages by removing all scripts. Normally it works fine but I prefer to block the scripts anyway in case it is not 100% reliable. Note that when scripts are not blocked, the CSP includes the `script-src` directive.

There's an hidden option `insertMetaCSP` to circumvent this issue (see https://github.com/gildas-lormeau/SingleFile/wiki/Hidden-options for more info). When set to `false`, the CSP won't be added in the saved page.

**Comment by bryanph** [comment]
That's fair, I think I can work around it and I guess it's a reasonable default on the security part
