### ISSUE TITLE
WashingtonPost Picture Distortion

### ISSUE THREAD

**Issue by sj365** [gildas-lormeau/SingleFile#1134]
https://wbai.org/program/?program=267
https://wbai.org/schedule/
https://www.washingtonpost.com/technology/2023/02/28/hologram-circus-animals-roncalli/

Singlefile is not capturing the wbai pages correctly.  One page the picture is omitted, the other page the schedule is distorted.  The WashingtonPost article is being saved with the mini picture stubs at the bottom expanded out of proper size.  I started noticing this  about a week or so ago.  This behavior is observed in most WashingtonPost articles checked.  **This issue is different from the previous WashingtonPost issues reported.

The options currently used are attached

Processor 11th Gen Intel(R) Core(TM) i9-11980HK @ 2.60GHz 3.30 GHz
Installed RAM 32.0 GB (31.7 GB usable)
System type 64-bit operating system, x64-based processor
Pen and touch Touch support with 10 touch points
Edition Windows 11 Pro
Version 22H2
OS Build 22621.1265

Chrome is up to date
Version 110.0.5481.178 (Official Build) (64-bit)

[singlefile-settings-2023-03-03T06_32_32.954Z.zip](https://github.com/gildas-lormeau/SingleFile/files/10878898/singlefile-settings-2023-03-03T06_32_32.954Z.zip)
[Screenshots.zip](https://github.com/gildas-lormeau/SingleFile/files/10878949/Screenshots.zip)

**Comment by gildas-lormeau** [comment]
You must disable `Images > save deferred images > zoom out the page` to fix the distortion issues. This is the default value. You should enable this option only if you're sure it works for the page you're saving.

To fix the missing image, you have to enable the option `Network > pass "Referer" header after a cross-origin request error` because the images are "protected".
