### ISSUE TITLE
Suggestion to support importing from a file.

### ISSUE THREAD

**Issue by StrollStars** [gildas-lormeau/SingleFile#1179]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
I want to import a list of URLs from a file and have SingleFile save each page that these URLs point to in sequence.

**Describe alternatives you've considered (optional)**
[Save Page WE](https://chrome.google.com/webstore/detail/save-page-we/dhhpefjklgkmgeafimnjhojgjamoafof), but its interface doesn't have Chinese.

**Additional context (optional)**
![2023-06-12_004058](https://github.com/gildas-lormeau/SingleFile/assets/10942225/2b9708f1-d68b-48be-bbad-4b14bf69599b)

**Comment by gildas-lormeau** [comment]
Thank you for the suggestion, right now I consider this feature is  out of the scope of the extension. I would prefer that you use a third-party extension like https://chrome.google.com/webstore/detail/open-multiple-urls/oifijhaokejakekmnjmphonojcfkpbbh to open the URLs from a file and then use "Save all tabs" in SingleFile. Overall, I prefer users to combine tools rather than code everything in SingleFile.

However, if you think this feature would really benefit from being integrated into SingleFile, please let me know.

**Comment by StrollStars** [comment]
@gildas-lormeau I looked into [Open Multiple URLs](https://chrome.google.com/webstore/detail/open-multiple-urls/oifijhaokejakekmnjmphonojcfkpbbh) and, according to your suggestion, it requires opening and saving all web pages at once, which has the limitation of the number of web pages that can be opened simultaneously. I need to save a very large number of web pages at once, usually over a hundred, so I hope that the URLs in the list can be opened, saved, and closed one by one in a loop.

**Comment by gildas-lormeau** [comment]
For this kind of usage, I would recommend to use single-file-cli. see https://github.com/gildas-lormeau/single-file-cli.

**Comment by StrollStars** [comment]
@gildas-lormeau Thank you for your help.
