### ISSUE TITLE
Ability to receive message from other extensions (e.g. Gesturefy)

### ISSUE THREAD

**Issue by scruel** [gildas-lormeau/SingleFile#1186]
**Is your feature request related to a problem? Please describe.**
I want to integrate SingleFile with [Gesturefy](https://github.com/Robbendebiene/Gesturefy), so that I can just save page(s) conveniently by mouse gesture, instead of move the mouse to a specific area (SingleFile icon) then click or use hotkeys, consider that browsers have more and more built-int hotkeys, which cause users have less custom-able hotkeys that can be trigger actions in convenient way, also, sometimes I don't want to put my hands on the keyboard while surfing pages only with mouses.
So, hope this feature can be supported, thanks!

**Describe the solution you'd like**
The excepted messages might can be:
```json
{ "target": "current_tab", "annotation": true  }
{ "target": "current_tab", "section": "selected" }
{ "target": "all_tab" }
```

**Additional context (optional)**
Gesturefy wiki: https://github.com/Robbendebiene/Gesturefy/wiki/Send-message-to-other-addon
Related to https://github.com/gildas-lormeau/SingleFile/issues/515

**Comment by gildas-lormeau** [comment]
Thank you for the suggestion. I implemented the feature and it will be available in the next version. To make things simple, I decided to use a "simple" string as message (instead of a JSON string). The value can be:
 - "save-page": save the current page
 - "edit-and-save-page": edit the current page in the annotation editor and save it
 - "save-selected-links": save the selected links
 - "save-selected-content": save the selected content
 - "save-selected-tabs": save the selected tabs
 - "save-unpinned-tabs": save the unpinned tabs
 - "save-all-tabs": save all the tabs

**Comment by link89** [comment]
I am new to userscript, is it possbile to make use of this design to ask SingleFile to download current page from a userscript?

**Comment by borensteinboar** [comment]
Aside from:
""save-page": save the current page
"edit-and-save-page": edit the current page in the annotation editor and save it
"save-selected-links": save all the links in the selected content
"save-selected-content": save the selected content
"save-selected-tabs": save the selected tabs
"save-unpinned-tabs": save the unpinned tabs
"save-all-tabs": save all the tabs"

is it possible to batch save urls by calling singlefile from another extension?
