### ISSUE TITLE
Failure to save comments and other elements on Reddit.com pages with the new layout

### ISSUE THREAD

**Issue by gom3sr** [gildas-lormeau/SingleFile#1206]
Hi, thank you for your awesome extension.

I'd like to ask for some help. Here are steps to reproduce the behavior:

1. Open a new private/incognito window in your favorite browser.
2. Browse any thread on Reddit. 
    For example, I've tested this one: https://www.reddit.com/r/revancedapp/comments/15326az/continue_using_your_favorite_thirdparty_reddit/

Here's how the page looks like in a browser

![Screenshot_1](https://github.com/gildas-lormeau/SingleFile/assets/36941220/13eb928a-f45d-42fb-a4ff-84af4e3a2ec2)
![Screenshot_2](https://github.com/gildas-lormeau/SingleFile/assets/36941220/9106d472-dcc3-4690-af6e-c9fcdd054d0e)

3. Save a copy of the page with SingleFile
Now here's how the saved page looks like:
![Screenshot_3](https://github.com/gildas-lormeau/SingleFile/assets/36941220/d3588760-6fd5-4c5b-925d-892fb7529218)
![Screenshot_4](https://github.com/gildas-lormeau/SingleFile/assets/36941220/95bbd261-7b0f-4b99-bd03-ae8c8cb68055)

The archived page is missing many elements, such as icons and the sidebars. But the most important thing that is missing is the comments. There is a large blank space in the place where the comments were supposed to be. 
I've tested with SingleFile reset to default settings. I've also tried unchecking the options "Network > blocked resources > scripts" and "HTML Content > remove hidden elements" and checking "HTML content > save raw page", as mentioned in the FAQ, but it didn't work. 

Tested with Firefox and Chrome on Windows 10.

**Comment by gildas-lormeau** [comment]
Thank you for the detailed report. It looks like it's a minor CSS issue actually. When the page is saved with SingleFile, the following CSS rule is saved into the page. Disabling this particular rule fixes the rendering issue. However, I don't know yet why it's present in the saved page. It's going to take a little more investigation on my part.

```css
:not(:defined):not(faceplate-auto-height-animator, 
faceplate-dropdown-menu, 
faceplate-expandable-section-helper, 
faceplate-hovercard) {
  visibility: hidden;
}
```

**Comment by gom3sr** [comment]
I made a quick test here. Disabling the CSS rule makes the comments appear, but the way they show up on the page is completely messed up.

![Screenshot_5](https://github.com/gildas-lormeau/SingleFile/assets/36941220/7fe8beb5-b990-4c3c-8b11-0eddcbbcbec1)

**Comment by gildas-lormeau** [comment]
I was able to identify the cause of the issue. Stylesheets uses the [`:defined`](https://developer.mozilla.org/en-US/docs/Web/CSS/:defined) pseudo-class to select custom tags like `<faceplate-timeago>`. The problem is that [`CustomElementRegistry.define()`](https://developer.mozilla.org/en-US/docs/Web/API/CustomElementRegistry/define) is not called when viewing a saved page. As a consequence, no elements are selected when using the `:defined`pseudo-class. Thus, in order to circumvent this issue, SingleFile will replace `:defined` with `*`. This fix works with the new layout of reddit (see attached zip file), it will be available in the next version.

[Continue using your favorite third-party Reddit apps after July 1 _ r_revancedapp (30_07_2023 22_46_19).html.zip](https://github.com/gildas-lormeau/SingleFile/files/12210108/Continue.using.your.favorite.third-party.Reddit.apps.after.July.1._.r_revancedapp.30_07_2023.22_46_19.html.zip)

**Comment by gildas-lormeau** [comment]
For the record, the version `1.21.59` fixes all the issues with the new layout in Firefox.
