### ISSUE TITLE
[1.21.60] Stuck in processing, page wont save on older firefox

### ISSUE THREAD

**Issue by RandomGOTI** [gildas-lormeau/SingleFile#1227]
**Describe the bug**
SingleFile 1.21.60 is stuck in Initializing (2/2) on older firefox

**To Reproduce**
1. Go to [google.com](https://www.google.com/)
2. Save page with SingleFile from the context menu or adding in batch save url
3. menu itemwill show Initializing (2/2) / and pending saves : processing

**Environment**
 - OS: Windows 7 Ultimate x64 SP1
 - Browser: Firefox
 - Version: 84.0.2 (64-bit)

**Additional context**
default settings
1.21.56 no issues

`Works with firefox 48.0 and later, android 48.0 and later` will the minimum firefox version be increased ?

**Comment by kalum88** [comment]
**Describe the bug**
Same for me. Since 1.21.60 on older Firefox the download process gets stuck and the page is not saved. 1.21.56 works.

**Example**
https://dennikn.sk/3534407/indicka-sonda-ako-prva-v-dejinach-pristala-v-okoli-juzneho-polu-mesiaca/

**SingleFile 1.21.60 and 1.21.62 - default settings**
Deferred images
Frame contents
... gets stuck. The page was not saved

**SingleFile 1.21.56 - default settings**
Deferred images
Frame contents
Step 1 / 3
Step 2 / 3
Step 3 / 3
The page was saved

**Environment**
- OS: [Android 13]
- Browser: [Firefox]
- Version: [68.11.0]

**Comment by gildas-lormeau** [comment]
Thank you. I was able to reproduce and fix the regression in Firefox 68. The fix will be available in the next version. It will probably be available for download in approximately one week on the Mozilla store.

Note that I do not test SingleFile in old browsers, so there's always a risk the same situation will happen in the future.

**Comment by gildas-lormeau** [comment]
FYI, the version 1.21.63 which fixes this issue is available for download on the store.

**Comment by kalum88** [comment]
Tested with version `1.21.63` and it works. Thank you very much for the fix. I will probably try to use SingleFile on Android with Firefox Nightly like you mentioned in this issue https://github.com/gildas-lormeau/SingleFile/issues/481

**Comment by gildas-lormeau** [comment]
@kalum88 Tank you for the feedback. Regarding Firefox for Android, you can wait a little bit, Firefox should allow you to install any extension very soon, see https://blog.mozilla.org/addons/2023/08/10/prepare-your-firefox-desktop-extension-for-the-upcoming-android-release/.

**Comment by 12sunflowers** [comment]
Android 10, Firefox stable and nightly stuck save at some pages

![Image](https://github.com/user-attachments/assets/7f569f92-9b17-4baa-a99f-b02385b7a578)

![Image](https://github.com/user-attachments/assets/8c178286-653e-4db9-9580-6f1900a90a71)
