### ISSUE TITLE
Page styled with Dark Reader saves original theme with HTML format, but dark theme with ZIP format

### ISSUE THREAD

**Issue by redactedscribe** [gildas-lormeau/SingleFile#1277]
**To Reproduce**
1. Install Dark Reader and enable dark mode.
3. Visit https://www.example.com/ (should now have a dark theme) and save page with file format HTML: Result is light/original styled page. (Save the page via the Annotation Editor.)
4. Save page with file format "self-extracting ZIP (universal)": Result is dark / Dark Reader styled page.

**Expected behavior**
Consistent page style colours in saved webpages regardless of save file format.

**Environment**
 - OS: Windows 11
 - Browser: Firefox
 - Version: 118

**Additional context**
It would also be cool to have an option for SingeFile to remove Dark Reader's styles before saving the page (to ensure the page is saved using its original styling).

Thanks.

**Comment by gildas-lormeau** [comment]
Thank you for the bug report. Unfortunately, I cannot reproduce the issue. On my end, the pages are both displayed in dark, which is actually the expected behavior. I attached the 2 files.

From a technical point of view, it's not possible to remove the styles added by Dark Reader because they cannot be identified in a generic way (that would work for all the same kind of extensions). A way to circumvent this issue would be to run a user script dedicated to this task before saving the page, see here for more info: https://github.com/gildas-lormeau/SingleFile/wiki/How-to-execute-a-user-script-before-a-page-is-saved.

[Examples.zip](https://github.com/gildas-lormeau/SingleFile/files/13040835/Examples.zip)

**Comment by redactedscribe** [comment]
> Make sure you disable Dark Reader when displaying the saved pages though.

I was worried that I might not have tested it with Dark Reader disabled so I just gave it a go: The ZIP version is dark while the HTML is still light. Interestingly, I just trying the two files from your Examples.zip and the same is happening... Why would your HTML version still display in light mode with Dark Reader disabled? Strange. Your/my saved webpage files in a Chromium browser are all dark, so something in my Firefox is the issue.

**Comment by redactedscribe** [comment]
I agree. This can be closed. Thanks @gildas-lormeau.

**Comment by gildas-lormeau** [comment]
You're welcome :)
