### ISSUE TITLE
Doesn't save some sites

### ISSUE THREAD

**Issue by turgay23** [gildas-lormeau/SingleFile#1355]
hi. I want to archive some pages on this site. I saved many pages, but some pages are not saved. I wonder if the problem is caused by me?
archive site: https://www.corelan.be/

unsaved pages:
- https://www.corelan.be/index.php/2009/09/05/exploit-writing-tutorial-part-5-how-debugger-modules-plugins-can-speed-up-basic-exploit-development/
- https://www.corelan.be/index.php/2010/01/09/exploit-writing-tutorial-part-8-win32-egg-hunting/

**Comment by gildas-lormeau** [comment]
Thank you for the bug report. Actually these pages can be saved but you have to be very patient. It takes approximately 2 minutes to save them. The problem is due to the presence of this image in the page: https://www.digiprove.com/images/dp_seal_trans_16x16.png which is causing a network timeout. This issue can be circumvented though, see https://github.com/gildas-lormeau/SingleFile/issues/935#issuecomment-1111099553 for more info.

**Comment by turgay23** [comment]
I just realized that www.digiprove.com is a server that does not exist. I removed those sites from the console and tried again. Thank you !

**Comment by gildas-lormeau** [comment]
Alternatively, if you're using an ad-blocker then adding "http://www.digiprove.com/" via a custom filter should also fix the issue. It works fine for example with with uBlock Origin, see settings > My filters.
