### ISSUE TITLE
Make the icons more beautiful! An icon replacement design is attached.

### ISSUE THREAD

**Issue by barrer** [gildas-lormeau/SingleFile#137]
**Describe the solution you'd like**
I use my only aesthetic, a more desirable one:
https://www.flaticon.com/free-icon/export_1263927

**Describe alternatives you've considered**
https://www.flaticon.com/free-icon/file_1091007
https://www.flaticon.com/free-icon/file_1102459
https://www.flaticon.com/free-icon/export_1263927
https://www.flaticon.com/free-icon/youtube_260421
https://www.flaticon.com/free-icon/document_1323978
https://www.flaticon.com/free-icon/website_1273179
https://www.flaticon.com/free-icon/file_1214765

**Additional context**
`Flaticon is the largest search engine of free icons in the world.`  
https://www.flaticon.com/about

I used the extension "https://chrome.google.com/webstore/detail/save-page-we/dhhpefjklgkmgeafimnjhojgjamoafof", but found that it uses Javascript to render reference resources. It has compatibility issues and is not ideal. 

Found this project today, very good, very pure html file, can be viewed offline on computers, mobile phones, iPads, etc. Thank you very much!

**Comment by gildas-lormeau** [comment]
I agree with you. I made the icon myself, 2 times, and I'm still unhappy with it. I must provide icons going from 16x16px to 128x128px. The problem I often encounter is the 16x16px image which is used in the toolbar because it needs to be "easy to read" (e.g. not blurry). I also need to integrate some kind of progress bar (it's done frame by frame today). I'll do some tests to see how well the one you propose integrates in the toolbar out of the box.

I do some efforts to produce HTML files as small as possible because it has always been an issue in the past. I did not like using JavaScript to group duplicate images, which is often a factor leading to large files. There has been a lot of trial and error (I tested "SVG sprites" before using CSS custom properties) and I'm quite happy with the current implementation. There are some other optimizations that help to remove unused CSS or HTML. They are quite effective sometimes. For example if you save a GitHub page with SingleFile, it will weight 4x or 5x less than the same page saved with the extension you cited.

**Comment by gildas-lormeau** [comment]
Here are 2 screenshots showing the icon in the Chrome toolbar on a Full HD screen. From my point of view, the arrow is not fat enough is the icon is a bit hard to recognize.

![screenshot-1](https://user-images.githubusercontent.com/396787/51566909-1eab9600-1e96-11e9-99f1-aa7877551a4e.png)
![screenshot-2](https://user-images.githubusercontent.com/396787/51566912-21a68680-1e96-11e9-915f-3e15086052d0.png)

**Comment by barrer** [comment]
Is this better?
![image](https://user-images.githubusercontent.com/30139527/51577783-11be8f00-1ef6-11e9-87cc-f57959c82c4c.png)
![image](https://user-images.githubusercontent.com/30139527/51577790-16834300-1ef6-11e9-93f2-804d3c3b42ce.png)
https://www.flaticon.com/free-icon/file_1091007

**Comment by barrer** [comment]
Perhaps instead of "icon_16_wait*.png", replace it with: 0...10...50...99...100/ok/err(error), badge text instead. This avoids processing the icon image.  
API:
https://developer.chrome.com/extensions/browserAction#method-setBadgeText

**Comment by gildas-lormeau** [comment]
@barrer I updated the icons with the ones you proposed in the version 1.9.39. They look fine to me. I integrated a progress bar in the icon for the wait*.png files.

**Comment by gildas-lormeau** [comment]
Note that you may need to restart the browser after the update. Feel free to close the issue if you think it's okay for you too.

**Comment by boweden** [comment]
Just wanted to add love the new icon theme :-)  In addition to looking nicer, it's also easily distinguishable from the Download icon that shows up when a file is being downloaded (in Opera)

**Comment by gildas-lormeau** [comment]
@barrer I declared all the icons in the default_icon property (see below) in the version 1.9.41. Please let me know if the icon is correctly rendered on your end.

`
  "default_icon": {
    "16": "extension/ui/resources/icon_16.png",
    "48": "extension/ui/resources/icon_48.png",
    "64": "extension/ui/resources/icon_64.png",
    "128": "extension/ui/resources/icon_128.png"
  }
`

**Comment by barrer** [comment]
@gildas-lormeau 
`version: SingleFile 1.9.41`
Toolbar icons, context menu displays are HD icons, and the effect is good!
![image](https://user-images.githubusercontent.com/30139527/51719925-5ed16b00-2086-11e9-94e6-7a2aee6ce055.png)
![image](https://user-images.githubusercontent.com/30139527/51719940-655fe280-2086-11e9-99ea-51bcabbaf0f9.png)
I closed this issue, thank you very much! 😊

**Comment by gildas-lormeau** [comment]
Great news! :)
