### ISSUE TITLE
Display the infobar content in the webpage. 

### ISSUE THREAD

**Issue by newscoder** [gildas-lormeau/SingleFile#1386]
**Is your feature request related to a problem? Please describe.**

I am using the SingleFile to collect web clips from multiple pages on one topic, so finally they will be merged into one .html file.
The problem is that when all .html files are merged, the infobar will be lost, and there is no information of the title/url/date for the web clips from multiple sources.

**Describe the solution you'd like**
Is that OK for the developer to add an option for the infobar, which allows the infobar content to be attached front/back of the clipped content and display?
In this way, the infobar content will not be lost when multiple.html files are merged.

**Thanks!** 

**Describe alternatives you've considered (optional)**

**Additional context (optional)**

**Comment by gildas-lormeau** [comment]
It's not an easy problem to solve because it highly depends on how you merge the pages. In fact, the infobar and associated info were not designed for this use case. For example, the info are added into a comment just before the `<html>` tag in the saved page, and there can only be one HTML tag in a web page. So, as things stand, it's not possible to have several independent pieces of information (i.e. one per page included) on the same page.

**Comment by newscoder** [comment]
Thanks for the comments!

Yes, I tried first in Windows 10 with the Pandoc to merge the .html files but the Pandoc cannot work properly. Then I tried some online merge tools but still the infobar of multiple.html files were missed after merging.

However, it seems this is not an issue under Mac (or Linux). 
First, I simply used the "cat *.html >all.html", the infobar was still missed or only the first .html file infobar was kept.
**But when I use the Linux version of Pandoc, the merged .html finally had all the infobar information attached at the end of each webclip.**

So, this issue was solved to some extent.
