### ISSUE TITLE
Cannot open as PNG

### ISSUE THREAD

**Issue by anedroid** [gildas-lormeau/SingleFile#1415]
When embedding image option is enabled, indeed PNG header is put at beginning of the file, however I am unable to open it in image viewer. I am however able to open the demo file at https://gildas-lormeau.github.io as: HTML, zip and PNG, so it's either bad settings or the extension itself.

**To Reproduce**
1. Go to extension preferences.
2. format: self-extracting ZIP file (universal)
3. don't append data: enable
4. embed image: enable
5. Save any web page
6. Choose any png image to embed
7. Change the file extension to png
8. Open the file

This bug has been reproduced both in SingleFile and SingleFileZ.

**Environment**
 - OS: Fedora Cinnamon
 - Browser: Firefox 123.0.1-1
 - Version: 1.22.43
 - Image viewer: Eye of MATE, Shotwell

Additionaly, why don't SingleFile just make a screenshot of the page?

**Comment by anedroid** [comment]
It now works. I have no idea what happened.

**Comment by gildas-lormeau** [comment]
Feel free to send the saved page with the bug if you still have it. Regarding the screenshot, the problem is that Chrome only offers a way to capture the visible part in the tab. However, it seems Firefox can do fullpage screenshots. I'll do some tests and if it works, i'll try to integrate this feature in Firfox.
