### ISSUE TITLE
SingleFile freezes when saving with Zotero Connector enabled

### ISSUE THREAD

**Issue by adomasven** [gildas-lormeau/SingleFile#1479]
Hi gildas,

We at Zotero have recently updated the Zotero Connector to use MV3. As part of that change, we had to reimplement our page translation architecture to run in an [sandboxed-eval iframe](https://developer.chrome.com/docs/extensions/how-to/security/sandboxing-eval). We have had users report that [having Zotero Connector enabled freezes saving with SingleFile](https://forums.zotero.org/discussion/115141/zotero-connector-conflicts-with-singlefile-extension-in-chromium-based-browsers), and I have confirmed that on the [linked medium page](https://phaylen.medium.com/the-15-most-beautiful-animals-in-the-world-ea92b2a03a4e). As the user reports, I indeed see some network activity related to our translation sandbox frame, and having inspected what's happening I have noticed that DOMContentLoaded event keeps firing on our frame, as if being refreshed.

I'm not sure if we're doing something wrong here, or if SingleFile is doing something weird with frames it saves (especially frames that belong to other extensions). Moreover, I'm not sure if SingleFile should be attempting to save frames from non https?:// origins, as it might cause issues with any other extension that uses the sandboxed eval frame too.

**Comment by gildas-lormeau** [comment]
Hi @adomasven,

I confirm I can reproduce the issue. I've done a debugging session. The issue is related to the `_setFrameAttributes` in the code of the connector, see https://github.com/zotero/zotero-connectors/blob/2325e9d2b20c9f80639063d71997868535935451/src/browserExt/zoteroFrame.js#L73C2-L83

The problem is that the attributes are updated **very** often even if they don't change. I was able to circumvent the issue by replacing the implementation with the code below (I've added some `if` instructions).

```js
_setFrameAttributes(attributes, style) {
  for (let key in attributes) {
    if (this._frame[key] !== attributes[key]) {
      this._frame[key] = attributes[key];
    }
  }
  if (!this._frame.getAttribute("id")) {
    this._frame.setAttribute("id", attributes.id);
  }
  for (let key in style) {
    if (this._frame.style) {
      this._frame.style[key] = style[key];
    }
  }
}
```

**Comment by gildas-lormeau** [comment]
It looks like the real issue is that the observer is never disconnected here https://github.com/zotero/zotero-connectors/blob/2325e9d2b20c9f80639063d71997868535935451/src/browserExt/zoteroFrame.js#L65-L70. I don't see the any exit condition.

**Comment by KaimingTao** [comment]
Confirmed, when uninstalled the Zotero plugin, SingleFile plugin works ok.

**Comment by adomasven** [comment]
@gildas-lormeau thanks for taking a look. I guess SingleFile is setting some attributes on all iframes that it's capturing which is causing this to run in the first place? The code you've discovered was recently added to prevent websites from accidentally "tampering" with the Zotero translation sandbox frame as that was causing it to take up empty space on some websites, but in my testing it wasn't causing things to run in an infinite loop. Either way, this should be easily enough resolved on our end.

**Comment by adomasven** [comment]
Zotero Connector will be fixed in the next release, pending Chrome extension store approval.

**Comment by gildas-lormeau** [comment]
@adomasven Thank you. I confirm that SingleFile adds an attribute containing an id on all frames in order to recognize them when processing the page.

Note that there is still a potential infinite loop here https://github.com/zotero/zotero-connectors/blob/b5cf8a0f326fc78ba4abcfa90b4cc9efd0a3ed57/src/browserExt/zoteroFrame.js#L66C4-L68 because `observer.observe()` is always called after `observer.disconnect()`. Ideally I think there should be a condition that would prevent `observer.observe()`to be called again (e.g. when everything is done) or maybe use a timeout to allow the CPU to do some work (e.g. let SingleFile process the page).

**Comment by adomasven** [comment]
Yes, that is intentional. The need to even have a mutation observer in the first place is because some websites change our iframes post page-load, and we can't know when, or whether they might decide to change them again (e.g. for navigation without page-load). I'm still not sure why SingleFile changing the id was causing an infinite loop. Is it repeatedly trying to change the ID too or something?

**Comment by adomasven** [comment]
You might still want to consider not saving extension frames in snapshots, but that should probably be a separate issue. Thanks for the help!
