### ISSUE TITLE
Cannot set in private mode

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [gildas-lormeau/SingleFile#152]
**Describe the bug**
The settings cannot work in Firefox private window.

**To Reproduce**
1. Go to hamburger button
2. Click on Open new private window
3. Go to about:addons
4. Scroll down to SingleFile, then click Options
5. See error

**Expected behavior**
All the options should display the text, and the settings can be stored.

**Screenshots**
All the options looks as blank, and no way to modify them.

**Environment**
 - OS: Win10 Home
 - Browser: Firefox 65
 - Version: 1.9.54

**Additional context**

**Comment by gildas-lormeau** [comment]
Thanks for reporting the issue. It is due to this bug on Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1329304. Is there a need for you to open about:addons page in a private window instead of a normal one?

**Comment by KrasnayaPloshchad** [comment]
I've heard this bug is also presented in Tor Browser, also, I saw other extensions as [RSSPreview](https://addons.mozilla.org/firefox/addon/rsspreview/) and [Save Page WE](https://addons.mozilla.org/firefox/addon/save-page-we/) doesn’t be affected, so I feel weird for this.

**Comment by gildas-lormeau** [comment]
This is due to the fact that SingleFile has not been developed to handle this particular bug in Firefox and that this scenario has not been tested. Historically, SingleFile was running on Chrome long before "Web Extensions" existed in Firefox. Even though it has been rewritten from scratch a little bit more than 6 months ago, it still inherits some code of its predecessor.

**Comment by gildas-lormeau** [comment]
It's fixed in version 1.9.55.
