### ISSUE TITLE
After updating, SingleFile keeps adding itself to Vivaldi's panels list and then opening its panel in all windows

### ISSUE THREAD

**Issue by unikitty37** [gildas-lormeau/SingleFile#1529]
**Describe the bug**
Since updating to extension version 1.22.57, it has added a panel to Vivaldi's list of panels, and auto-opens the panel in every window. If I right-click on the panel and choose Edit > Remove from Toolbar, it does not stay removed, but instead reappears after a few hours — and auto-opens the panel in every window again.

**To Reproduce**
Steps to reproduce the behaviour:
1. Install Vivaldi with an older version of SingleFile.
2. Use Vivaldi normally.
3. Wait for Vivaldi to auto-update SingleFile.
4. The SingleFile icon has now been auto-added to the panels list without user consent, and the SingleFile panel now opens in every window.

**Expected behaviour**
If SingleFile is in the panels list, it does not open the panel automatically; it _only_ opens the panel when the user explicitly clicks on the icon in the panels list.

If SingleFile has been removed from the panels list, it stays removed.

SingleFile should _not_ just add itself to the panels list when the extension updates. It should respect the user's configuration and not change it.

**Screenshots**

**Environment**
 - OS: macOS 14.5 (23F79)
 - Browser: Vivaldi
 - Version: 6.8.3381.48
 - Extension Version: 1.22.57

**Additional context**

This is sufficiently intrusive that the only workaround is to keep SingleFile disabled in the Extensions window and only enable it when I need to save a page.

**Comment by gildas-lormeau** [comment]
Thank you for the detailed report;

This is due to the fact that I migrated SingleFile to the Manifest V3 and I had to update SingleFile multiple times during the last hours to fix minor issues. Unfortunately, the behavior you're describing seems to be a bug in Vivaldi and I don't know how to circumvent it.

**Comment by unikitty37** [comment]
Thanks — I'll open a bug with Vivaldi, in that case, and leave SingleFile disabled when I'm not using it until things have had a chance to settle down 😁

**Comment by gildas-lormeau** [comment]
I'm really sorry, and I confirm that the problem occurs every time I reload the extension in developer mode. I had no choice but to migrate to Manifest V3. Users were starting to complain that I hadn't done so, because Google started issuing warnings in Chrome a few weeks ago. Get ready for the big MV3 fiasco...

**Comment by unikitty37** [comment]
Yes, I've just done a `sudo apt-mark hold chromium` on the Linux boxes to keep uBlock Origin working happily. Let's see if Vivaldi, who were talking about continuing MV2 support alongside MV3, manage it, or if I have to switch to Firefox.

I don't think you can track other people's Vivaldi issues (it's hard enough to see what's happening with your own!) but it's raised as VB-108469, for reference.

**Comment by unikitty37** [comment]
…actually, it's doing it in Chromium as well, so I guess it's not just Vivaldi.
