### ISSUE TITLE
I want it for Firefox

### ISSUE THREAD

**Issue by lagleki** [gildas-lormeau/SingleFile#16]
Why not port it to Firefox?

**Comment by fwolf** [comment]
Same with @stephenjudge using UnMHT, but data URI html has better support by various browser, make this firefox extension is a good idea.

**Comment by franzalex** [comment]
@dmitryTsatsarin: while MAFF is good for what it does, it requires the extension to be installed on a user's computer. Otherwise you'll have to inform the recipient to change the extension to .zip, and then open the files. Yes, it is possible to do but it is quite cumbersome, especially since not eveyone is tech-savvy.

**Comment by ctrl8511** [comment]
agreed so much! 
MAFF can only be seen by firefox instead of SINGLEFILE that can be opened by ANY browser, also without this ADDON.

please make it for firefox

**Comment by gildas-lormeau** [comment]
It's fixed in 1.0.13.

**Comment by gildas-lormeau** [comment]
You can download the extension from https://addons.mozilla.org/en-US/firefox/addon/single-file.
