### ISSUE TITLE
Could the clipped single-page be saved to the clipboard of the operating system?

### ISSUE THREAD

**Issue by waynesonia** [gildas-lormeau/SingleFile#163]
Hello,  it may be more flexible if the clipped page be saved to the system's clipboard rather than be saved to the disk, for the data in the clippboard would be used in other apps such as a rich-text web-note app. This is my suggestion, thanks

**Comment by gildas-lormeau** [comment]
Hi, thanks for your suggestion. I find this feature interesting and it looks like it's indeed technically possible without requiring additional permissions when installing the extension. I need to do more tests to see if I can integrate it as an option, i.e. if it would make any sense when auto-saving pages or saving multiple tabs. Otherwise, the feature would be available with the context menu I think.

**Comment by gildas-lormeau** [comment]
So I did some tests in Chrome and Firefox and I have some bad news. Currently, support for adding HTML content to the clipboard is non-existent. I may have done something wrong, but I'm afraid you may have to wait a while for this feature to exist.

**Comment by waynesonia** [comment]
Bad news..but it's OK~ Thanks for your trial, I guess this might be cause by permission of memory access? Anyway, I can wait for further news, hoping it would be good news next time ^_^

**Comment by gildas-lormeau** [comment]
Good news! My tests were wrong. The new option "misc. > save to clipboard" will be available in the the version 1.10.0.

**Comment by gildas-lormeau** [comment]
Will I regret it? Maybe...

![image](https://user-images.githubusercontent.com/396787/55013859-44663000-4fea-11e9-85dc-2d72b5ef1f95.png)

**Comment by waynesonia** [comment]
My god... is this caused by the addition of the function 'copy to clipping board'? Sorry to hear that...

(and felt sorry to reply so late. During these days I was busy doing something else)

At 2019-03-27 00:12:07, "Gildas Lormeau" <notifications@github.com> wrote:


Will I regret it? Maybe...

**Comment by gildas-lormeau** [comment]
Don't worry, I knew what I was doing. I knew this would happen because that's not the first time I add a permission to SingleFile, and I don't regret it ;) 

Here are the updated stats below, they're not dramatic (much less dramatic than when SingleFile requested the "downloads" permission)

![image](https://user-images.githubusercontent.com/396787/57137553-7c624f00-6db0-11e9-8c46-fcba260f07f0.png)
