### ISSUE TITLE
Show the progress of tabs saving

### ISSUE THREAD

**Issue by user471** [gildas-lormeau/SingleFile#176]
**Is your feature request related to a problem? Please describe.**
When I click Save all tabs the icon show `...` then `OK` even if SingleFile continues saving other tabs

**Describe the solution you'd like**
It would be better to show something like X/N where N - total number of tabs and X - how many tabs was saved.

**Comment by gildas-lormeau** [comment]
Thanks for the suggestion. Actually, that feature existed in the old version of SingleFile (version 0.x). I understand it's still useful. I'll try to re-implement it.

**Comment by gildas-lormeau** [comment]
I did some tests I'm a bit afraid this feature would have a negative impact on performances. The problem is that the label would have to be refreshed every time a page is being processed or each time it has finished *for every tabs*. If I try to refresh the label, lazily, only when the user selects the tab, the user sees the label being refreshed, and the user experience is not great. So I have to be "pro-active" and refresh all the labels for every tabs before the user select any tab. Unfortunately, I think this could lead to performance issues when a lot of tabs are being saved.

**Comment by user471** [comment]
@gildas-lormeau 
>So I have to be "pro-active" and refresh all the labels (when the value goes for example from "14/24" to "13/24") for every tabs.
What do you mean by all the labels? Isn't is just one label on SingleFile icon in browser menu?
Anyway you could create a checkbox in options so users could decide if negative impact worth it.

**Comment by gildas-lormeau** [comment]
You have one label per tab, because each tab can display a different thing. Adding a new option could solve indeed this issue, but there are already a lot of options. I'll see...

**Comment by user471** [comment]
@gildas-lormeau Another solution would be to use one label when 'save all tabs' is used. I don't think the information about individual tab is very useful in this case.

**Comment by gildas-lormeau** [comment]
@user471 Actually, there is a bug in the Chrome implementation that prevents to code this feature efficiently. I just did (again) some tests to be sure and I confirm I cannot implement your feature request without refreshing all the tab labels separately each time the value change or each time you do an action like selecting, creating, removing a tab...
FYI, the bug is that if you pass a (non-null) value to the [`setBadgeText`](https://developer.chrome.com/extensions/browserAction#method-setBadgeText) method, it's impossible to reset it. This breaks a feature that could allow to set a default value for all tabs (e.g. the number of tabs being processed) when there are no label displayed in one of them (e.g. when the tab is idle).

**Comment by user471** [comment]
I start using cli when I need to save many tabs. I think it's a better approach, so maybe this feature isn't necessary.

**Comment by gildas-lormeau** [comment]
@user471 The next version for Chrome will have a new feature that could interest you. You'll be able to view the pending saves into a separate window via selecting "View pending saves.." in the context menu. It should be available for download in one week. If you're using Firefox, you can already use this feature but it's a little bit buggy in the version currently published. The version implementing the fix is also in pending review. I hope it will be published in the coming days.
