### ISSUE TITLE
Auto close tab

### ISSUE THREAD

**Issue by sutrisnob45** [gildas-lormeau/SingleFile#185]
please add option to automatically close tab that has been auto saved

**Comment by gildas-lormeau** [comment]
Thanks for the suggestion. Can you give me more details and illustrate it with an example please?

**Comment by gildas-lormeau** [comment]
I'm closing the issue because, from my point of view, the whole point of the "auto-save" feature is to save pages while navigating from page to page. In such cases, you don't want the extension to close automatically tabs. Feel free to re-open the issue if there is a misunderstanding.

**Comment by doplu** [comment]
Hello,
This would be useful when someone works with a lot of tabs. Example : you read a lot of articles. You have finished to read one openned article webpage in a tab. You hit your Shortcut for SingleFile and it saves the page and close it alone. So you can continue to read another of your already openned tab you have to read. ;)

**Comment by gildas-lormeau** [comment]
I think the idea could be interesting but maybe in another extension which would be dedicated to this usage. It could be based on SingleFile code or communicate with the SingleFile extension.

**Comment by doplu** [comment]
Thanks.;)
If one creates another extension just for closing the current tab, it kills the goal imho to have the webpage saved and closed with only one click (or one keyboard shortcut) !

Apparently, creating an extension wich would do the following is not possible (see https://stackoverflow.com/questions/36902913/is-it-possible-to-execute-another-chrome-extension-using-your-own-chrome-extensi) ?: 
1) running SingleFile for saving as html file
and then running another extension in order to :
2) save the page as a pdf file (https://github.com/gildas-lormeau/SingleFile/issues/207)
and then running another extension in order to :
3) "close the current tab"

**Please note that it is possible to do the above 3 steps with 3 shortcuts:**
1) Ctrl+Shift+Y
2) Ctrl+P 
(You have to first configure Google Chrome : Change the "Google Chrome shortcut" "target" bar with the following : "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --kiosk-printing
See here for more info: https://winaero.com/blog/how-to-create-pdf-files-natively-and-turn-off-print-preview-in-google-chrome/ and https://peter.sh/experiments/chromium-command-line-switches/ 
When you hit Ctrl+P Google Chrome automatically prints a "save as pdf" page and saves it in the default Chrome folder. Alas the name of the pdf is the title of the webpage which can cause problems with accents and long page titles...)

3) Ctrl+W


I would dream of an extension which would execute such keyboard shortcuts by itself with only one click (or shortcut) ! ;)

**Comment by gildas-lormeau** [comment]
The option "auto-close the tab after the page is saved" which will be available in the version 1.11.32 will allow you to automatically close the tab after saving the page.
