### ISSUE TITLE
new version 0.3 does not work with gmail

### ISSUE THREAD

**Issue by spunkyy** [gildas-lormeau/SingleFile#2]
hi there, i'm a great fan of singlefile, i've been using it for over a year. however, the new version 0.3 does not work with gmail. 

normally i save single gmail web emails by clicking on 'Print' in gmail, which opens up 2 new tabs, the email itself and another tab showing print options. then i use singlefile on the email, and 'save as'.

in the new version 0.3 singlefile, when i click on singlefile it works. but when i try to save it, it does not work:
1. when click on the banner, it saves a webpage but with an extra folder containing all the images
2. when i uncheck 'display save banner' and 'display save notification' (according to your instructions), then click 'save as' in chrome, it saves a 0 kb file.

i have also tried looking for a place to reinstall the previous version of singlefile (0.2.33) but i cannot find this.

please help!! :) thank you for creating a great product :D

yy

sent 2011-11-21

**Comment by terrypin999** [comment]
When I use Single File on this page
https://www.thingiverse.com/thing:1264391
the saved file does not display the large image near the top, which remains black.

**Comment by gildas-lormeau** [comment]
@terrypin999 I cannot reproduce the issue. I did the test in the latest versions of Chrome and Firefox with the default settings in SingleFile. What browser are you using? Did you change any setting in SingleFile?

**Comment by terrypin999** [comment]
Thanks, appreciate the quick response. I’m using Waterfox (classic) and have not knowingly changed any settings in Single File. Is there any file, screenshot or other information I can send to help isolate the problem?

BTW I also opened the HTML in Chrome but that black rectangle was still displayed.

**Comment by gildas-lormeau** [comment]
@terrypin999 Thank you for the additional info. I was able to reproduce the issue. 

This is due to the fact that SingleFile transformed the image as a background image. It's an optimization used to reduce the size of the saved page when images are repeated. Unfortunately, the maximum size of the background image is limited in Waterfox Classic. That's why you see this bug. To disable this optimization and fix it, uncheck the option `Images > group duplicate images together`.

**Comment by terrypin999** [comment]
Thanks, that fixed it!

I’m unfamiliar with GitHub and find its navigation difficult. I assume the reason my ‘issue’ is not in the current list under Open is because it is related to another that is Closed? How do I quickly find that please? And do developers prefer answers by email or in GitHub?

Also, I’m puzzled about the connection with Gmail?

Best Wishes,

--
Terry

**Comment by gildas-lormeau** [comment]
I'm glad to hear it! :)

Actually, you should indeed have created a new issue on GitHub. That's why you have some difficulties to find it, I guess. The current one was created in 2011 and was describing a bug with GMail. Note that's not a problem for me since I'm notified when any issue is updated. However, it might be hard for another user having the same question to find the current discussion.

You can reply on GitHub or by email to an issue, the result is the same. In both cases, the message will be posted on GitHub, see https://github.com/gildas-lormeau/SingleFile/issues/2#issuecomment-800183677.
