### ISSUE TITLE
Suggestion : Also save as a pdf file ?

### ISSUE THREAD

**Issue by doplu** [gildas-lormeau/SingleFile#207]
Hello,

_**Is your feature request related to a problem? Please describe.**_
Yes. I would like to able to view and make keyword searches in Google Drive for files that I have saved. Alas html files cannot be searched or previewed correctly in Google Drive.

_**Describe the solution you'd like**_
I would like that SingleFile save the webpage as html and also as a pdf file (derived from CTRL+P ?)

_**Describe alternatives you've considered (optional)**_
I realize that when digging in my html archives over the years, sometimes the html isn't really well rendered into the (current or old) browser.
Sometimes the interesting part was not saved ! If I had a pdf version (or maybe a not text OCR png version ? ) of the scrolled webpage maybe it would have been saved and could be easily displayed now ?
Well, I guess that the hard parts when saving webpages is being pretty sure that they are as complete as possible and ....being able to open them years later ! 

_**Additional context (optional)**_
I am currently using Google Chrome on a Windows pc.

So from what I understand in Google Chrome one can save a webpage as :
- html
- mht
- pdf CTRL+P
- scrolling screenshot png ?

Thanks in advance ;-)

**Comment by gildas-lormeau** [comment]
Thank your for your suggestion. The page saved in HTML with SingleFile is supposed to be better in terms of fidelity compared to the original. That's why SingleFile exists. Before creating SingleFile, I noticed that pages saved in PDF were far to be perfect and MHTML did not exist in Chrome (in 2010). So I created SingleFile to save entire pages in HTML. That's the first extension which implemented this feature. That's also the whole purpose of this extension.

If you get a page that is corrupted when saved with SingleFile, there are great chances it would be corrupted in PDF. From my point of view, the real issues you're having are these ones:

 * Google Drive cannot work with HTML pages
 * Some of your old saved pages in HTML are corrupted

I can fix the second issue when you encounter it. My goal is that pages saved with SingleFile are the most accurate compared to MHTML and PDF. Unfortunately, I cannot fix the first one.

**Comment by Raytle** [comment]
[ArchiveBox](https://github.com/ArchiveBox/ArchiveBox) has this feature.

**Comment by beedell-roke** [comment]
@gildas-lormeau, I've use for this: to save my resume, written in HTML+CSS+JS, as an `application/pdf`. No alternative format is accepted for most applications (except, occasionally, `application/vnd.openxmlformats-officedocument.wordprocessingml.document`). Currently, my workflow is really fragile, due to how Chromium and Firefox have a hard limit on page length, even when the `@page` length is dynamically applied in JS.

`pandoc` produces hideous results, yet it's the sole alternative that I know of.
