### ISSUE TITLE
option to save ONLY HTML to reduce file size

### ISSUE THREAD

**Issue by avidh** [gildas-lormeau/SingleFile#223]
It would be awesome if it can provide option to only save the open tabs' html as it is, without including the css, etc so that file size will be smaller.

I was looking for a way to scrape the website contents for all open tabs so I don't really care about broken style or images.

Right now, this plug-in creates close to 600K file but a simple HTML file save is less than 200K.

Thank you in advance for your consideration.

**Comment by gildas-lormeau** [comment]
Thank you for your suggestion. I'm unsure I'll implement your feature request. The whole point of SingleFile is to embed resources into saved pages. This is not easy and that's the purpose of the extension. The fact that it is able to save multiple tabs is a bonus. Maybe this project https://github.com/gildas-lormeau/SingleFileZ would interest you more. Since it produces zip files, it could be easy for you to create a script (e.g. a batch/bash script) which would removes from zip files all the resources you wouldn't want to save.

**Comment by AdKiller** [comment]
Since you can save HTML page only using your browser, there is little point in including it in this addon.

**Comment by gildas-lormeau** [comment]
@avidh I recommend you to take a look at https://github.com/lewisl9029/just-save-webextension, it should solve your issue.

**Comment by gildas-lormeau** [comment]
@avidh The new feature I added in the last version should fix your isssue. I recommend you to read https://github.com/gildas-lormeau/SingleFile/wiki/How-to-execute-a-user-script-before-a-page-is-saved. To remove all the images and the styles from the saved page, replace `"img"` in the example (part 5) with `"img, style, link[rel=stylesheet]"`.
