### ISSUE TITLE
Enable Autosave by Defualt for certain URLs

### ISSUE THREAD

**Issue by MetalOctopus** [gildas-lormeau/SingleFile#233]
Hi, this is a great addon, thanks very much for your work on it.

I like the profile feature for specific URLs, but have noticed I still have to go and switch auto save on before the periodic saving begins. Would it be possible to enable Auto Save by default?

Thanks for the help

**Comment by gildas-lormeau** [comment]
Actually that's possible but it's a bit ugly. By using `regexp:`, you can prioritize a rule. The idea is to create a simple rule (i.e. not based on `regexp:`) telling that the auto-save is disabled for all domains. Then (this is the ugly part) you can add URLs to auto-save by using `regexp:` (e.g. `regexp:github` to autosave pages on github).  Finally, you just have to activate "Auto-save all tabs" or "Auto-save all unpinned tabs" via the menu. This selection will persist after restarting the browser.

Here is an example of settings (in the zip file) that you can import [singlefile-settings.zip](https://github.com/gildas-lormeau/SingleFile/files/3341117/singlefile-settings.zip)

I'll try to see if here is a way to avoid using the `regexp:` trick. Do you think that would be okay for you then?

**Comment by gildas-lormeau** [comment]
@MetalOctopus I simplified things. Now you're not forced to use the `regexp:` operator. You can also use "*" (instead of "." in my previous answer) to define a profile by default for all urls.  Finally, by using 2 profiles, you can use the context menu to add a URL in the whitelist (cf "Select the profile of the current domain" > "Auto-save" in my example) without going into the options page and typing the domain name.

Here is the example of settings file [singlefile-settings.zip](https://github.com/gildas-lormeau/SingleFile/files/3342398/singlefile-settings.zip)

Please let me know if you think this fixes your issue.

**Comment by gildas-lormeau** [comment]
I consider this feature is fixed, that's why I'm closing it. Please feel free to re-open it if necessary.

**Comment by MetalOctopus** [comment]
Hi Gildas - Sorry for the late reply but I managed to get it working following your instructions and the json file provided.
Thanks so much for the help!

**Comment by gildas-lormeau** [comment]
@MetalOctopus you're welcome!
