### ISSUE TITLE
Floating menus miss place after save

### ISSUE THREAD

**Issue by MrkTheCoder** [gildas-lormeau/SingleFile#235]
Hi 

I do not know anything about web page design! Sorry if I do not know the correct name for those menus or the problem I have! (Please feel free to change the **Title** to proper one)

At this [link](https://www.hackster.io/Pedro52/arduino-esp32-diy-water-level-sensor-and-diy-level-indicator-3d513d), Please check both left and right menus. At Left what ever are under "**Overview**" and at right side what ever are under "**RELATED PROJECTS**". 
Then try to scroll up and down to see how they behave and place on the page!

**Describe the bug**
After saving the page in single html, and open that file, those two menus placed on top of page and wrong place! (Over other menus and texts and ... Please check the screenshot)

**Expected behavior**
Is it possible to fix this problem!?

**Screenshots**
https://ibb.co/YpCrzgg

**Environment**
 - OS: Windows 10 Enterprise x64 1607
 - Browser: Chrome v75.0.3770.100

Thanks in Advanced

**Comment by gildas-lormeau** [comment]
Hi, your issue is due to the fact you scrolled down before saving the page and that SingleFile removes JavaScript scripts from the page. If you scroll to the top of the page before saving it, the elements will be placed correctly.
I'm wondering SingleFile should have an option to scroll automatically to the top of the page before saving it? I'm not very tempted, though...

**Comment by MrkTheCoder** [comment]
@gildas-lormeau 
Thanks for your answer. It workded!
