### ISSUE TITLE
Website Download Feature

### ISSUE THREAD

**Issue by viaahmed** [gildas-lormeau/SingleFile#239]
error_Comment

**Comment by viaahmed** [comment]
Hi Bro
Can you make an forked version with Website Download (partial or full).
I am a beginner in coding, I was going through [w3schools](www.w3schools.com), I desired to save the whole website for off-line reading, I searched for softwares and extension, then I got [this](https://github.com/gildas-lormeau/SingleFile) extension.
Yours is cool & very useful, I appreciate all the contributers to maintain and upgrade it.

The Model i am suggesting could work like this:

1. On a tab, Clicking on the extension (or context menu) may give us option to save the website's all pages or some (specified by directories).
2. The extension may then call an API to retrieve the sitemap of the website and display to get users assent(selection).
3. One by one fetch all files and pass through "SingleFile" to save them in a folder with the name of the website in file tree order.
4. There may be another worker which may identify common files and change the 'link' in the pages according to our local folder.
5. And whatever necessary...

This may make this extension more feature-some and competing with softwares like [HTTrack](https://www.httrack.com/).
Waiting for your response, Thanks

**Comment by gildas-lormeau** [comment]
Thanks for the suggestions. Actually, I think the work required to code your features is non-negligible and I'm not sure I'll have the time to code a crawler based on SingleFile soon. I'm also quite hesitant to release such product into a form of a Web Extension. I think a program running from the command line may be more appropriate.

**Comment by gildas-lormeau** [comment]
I'm closing this issue but I've opened the same one on the issue tracker of SingleFileZ, cf. https://github.com/gildas-lormeau/SingleFileZ/issues/21.

**Comment by doplu** [comment]
Hello, for me one of the main advantage of using SingleFile for grabbing a website would be having only one html file instead of 10 or 20 or... times more (not counting subfolders!) for each webpage of a website (which is what I usually get by using httrack currently- and when you have quite a lot of crawls it helps later on to have much less files for instance for saving the files online ; or indexing the content of the files ; or easily find and open the file directly inside google drive ...etc... ). It could be a CLI on windows with headless chrome browser for instance (??). Note: I would prefer not using a zip file with many small files inside them. Thanks in advance  ;)
ps: I know that httrack files can be converted later on to (single) warc files with some teaks but I much prefer your singlefile concept : it is as easy as a pdf screenshot of a webpage with text content already indexed (and image included) so I can then find and open the file easily with keyword(s) searches. So thank you for all you have already done ! ;)

**Comment by gildas-lormeau** [comment]
@doplu It's not really technically possible to store multiple pages in the same HTML page. On paper, that would be possible with SingleFileZ. However, note that SingleFile can be run from the CLI and can crawl a website, see https://github.com/gildas-lormeau/SingleFile/tree/master/cli.

**Comment by doplu** [comment]
Hello @gildas-lormeau,
 _It's not really technically possible to store multiple pages in the same HTML page._ 
It is not what I had in mind ! I thought of just saving one singlefile file for each html page. ;)
 Many thanks for the CLI link. I'll try to make it run on windows. ;)

**Comment by gildas-lormeau** [comment]
That should run fine, its' the OS I'm using ;)
