### ISSUE TITLE
Addons Manager Becomes Unresponsive / Freezes

### ISSUE THREAD

**Issue by gitgiggity** [gildas-lormeau/SingleFile#282]
When [some pages](https://answers.unity.com/questions/1606222/mutex-on-linux.html) are saved and then reloaded from file, firefox addons manager becomes unresponsive. All addons stop working, for a short period.

I've been scratching my head for days, trying figure this one out.

Could it be a related to issue with #225 ?

What do you make of it @gildas-lormeau ?

**Comment by gildas-lormeau** [comment]
The bug #225 is related to the fact that, in Firefox, the API that allows to [block or intercept HTTP requests](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Intercept_HTTP_requests) is very slow when the intercepted requests are [data URLs](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URIs).

To know if it's related to #225, you can try to do the same test with [SingleFileZ](https://github.com/gildas-lormeau/SingleFileZ). This extension uses [Blob URLs](https://www.w3.org/TR/FileAPI/#url-intro) instead of data URLs. Otherwise, you can try to disable all the extensions that block/intercept HTTP requests (e.g. ad blockers) and see if that makes a difference.

**Comment by gitgiggity** [comment]
I tried again after disabling NoScript, uBlock Origin, and HTTPS Everywhere, but the problem remained.

I then tried SingleFileZ, which works just fine without any unresponsiveness. Except for a little moment (that looks like one second or less) when the SingleFileZ page is blank, then rendered without styles, then finally rendered completely.

It looks like firefox poor handling of data URL is the source of the problem.

**Comment by gildas-lormeau** [comment]
That's weird that using SingleFileZ fixed the issue but not disabling the extensions you mentioned. I was not expecting this result. If you feel the courage, you could do this test again but disable all your extensions. Actually, I'm not convinced right now that the cause of your bug is exactly the same than #225 and I'm also wondering if a comment should be added to [the bug on the Firefox issue tracker](https://bugzilla.mozilla.org/show_bug.cgi?id=1557300).

The delay you see when opening the page saved with SingleFileZ is normal. This corresponds to the time needed to decompress the page and its assets. There's also some flickering, I don't know how to avoid or minimize it unfortunately.

**Comment by gildas-lormeau** [comment]
You're welcome!

There's maybe still a a way to fix the issue yourself if you want (if we consider this is the same bug than #225). You can download the zip file of the extension (I use [CRX Viewer](https://addons.mozilla.org/en-US/firefox/addon/crxviewer/) for this) and replace in `/js/backckground/media.js` the 3 occurrences of `["<all_urls>"]` with `["*://*/*"]`. Then, you can load manually the extension in about:addons by selecting "Debug add ons" in the menu at the top right of the page, and select the `/manifest.json` file of the extension. If this fixes the issue, you can contact the author to suggest him the fix or [upload your modified version on the store](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/Distribution) (you are not forced to distribute it though). Thus you would not need to re-install it each time you restart the browser.

**Comment by gitgiggity** [comment]
I don't think this person is the author, or even a software developer.
Their support link, on addons mozilla com, goes to a stupid click-bait website.

Seems like a scammer that stole someone elses code, and propably laced it with spyware.

I think I'll just look for some other addon for videos, since the original addons is basically discontinued.

**Comment by gildas-lormeau** [comment]
Indeed, the way this extension appeared on the store seems suspicious... I hope you'll be able to find a good replacement extension!

**Comment by rezad1393** [comment]
> Right!
> 
> I performed the tests you suggested, and narrowed the problem down to [Flash Video Downloader](https://addons.mozilla.org/en-GB/firefox/addon/flash-videodownloader/) ...(sorry mozilla for blaming firefox, XD)
> 
> Damn, I really liked that addon. And now people are complaining in the reviews that the latest version was uploaded by a fraudster. I had assumed that mozilla were very strict against such things (security violators). Sigh!
> 
> Thanks again @gildas-lormeau for your help.

a bit of advice.
your base standard (the least acceptable standard) for firefox addon should be that they should be opensource.
try not to install addons that have no source available to you.
