### ISSUE TITLE
Support Chrome Sync from the user settings

### ISSUE THREAD

**Issue by AliM1988** [gildas-lormeau/SingleFile#296]
In Chrome, I enabled Syncing to Google Account feature, so I have all Chrome settings and Extensions in multiple devices with same Google Account signed in. But the settings of SingleFile are not synced. And sometimes I see the profiles that I created and their rules that I set to domains is cleared! It's very good idea that these settings are synced through Google Account Syncing feature.

Maybe it is sort of a bug: "sometimes I see the profiles ... is cleared!" I wonder after updating Extension the settings are reset or is related to  Google Account Syncing feature. Already that I wrote this text, my all settings are reset. ;)
Regard

**Comment by gildas-lormeau** [comment]
I did not implement this feature because I was not sure it was an opt-in feature. I do not want to force users to sync their settings with third-party servers by default.

Profiles and rules should not be arbitrary cleared. That's indeed another issue that I've never encountered. Please create a new issue for this bug.

**Comment by gildas-lormeau** [comment]
The option should be in the version 1.13.14. You will have to wait 1 or 2 weeks before it's available for download.
