### ISSUE TITLE
Feature Question - saving existing bookmarks

### ISSUE THREAD

**Issue by anthonyclarka2** [gildas-lormeau/SingleFile#320]
Hello,

First off I wanted to say that I'm very grateful for you writing this amazing extension. It's really useful!

I was wondering if this feature was available or if there's a way to script or automate it:

When I bookmark a page, I'd like a copy automatically saved.

I'm assuming that there's probably not an easy task, is there an event that is fired when a page is bookmarked?

Thank you!

**Comment by gildas-lormeau** [comment]
Thank you for the suggestion and the link words. Your suggestion is interesting, I'll try to see if it could be implemented first. The event exists so it should be implementable, cf. https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/bookmarks/onCreated.

**Comment by gildas-lormeau** [comment]
After some looking more closely to the API, I noticed that the event triggered when a bookmark is added does not contain any info about the tab which was (eventually) used to bookmark the page.
The problem is that SingleFile needs the page to be displayed in a tab to save it faithfully. So, it means that SingleFile will have to compare the URL of the page added in the bookmark (this info is present in the event) and the URLs of the opened tabs to determine which tab to save. It's a little twisted, but it would work, I guess.

**Comment by gildas-lormeau** [comment]
The feature is implemented in the version 1.15.0 that I just uploaded on the store of Mozilla. You'll have to wait a little bit before it's available for download because of the manual review of the code (this is mandatory for recommended extensions). I also integrated this feature in SingleFileZ which is already available for download (nominally, the code is not reviewed). For Chrome, I need to wait for the pending reviews before I can upload the new versions. I hope the update will be available in one week approximately on the store of Google.

**Comment by gildas-lormeau** [comment]
I updated today the extension on the store of Google. The version 1.5.1 with this feature should be available for download in 7-10 days on Chrome.

**Comment by sterbalr** [comment]
This is amazingly cool

now will it download my bookmarks when I add a link to my bookmarks to my bookmarks?

chrome://bookmarks/

**Comment by gildas-lormeau** [comment]
Yes but it will work if and only if the page you're adding in the bookmarks is displayed in a tab when you bookmark the page.
