### ISSUE TITLE
Update saved SingleFiles + Node App

### ISSUE THREAD

**Issue by alivefromupstairs** [gildas-lormeau/SingleFile#338]
**The Problem**
I have a good amount of saved news pages, articles, and hacker news posts and they often have updated content (articles get updated with comments from parties interested and new comments in forums and so on)

I would like to update them all in a big swoop in a comfy terminal.

**The solution I'd like**
- SingleFiles to have a link somewhere in the markup, accessible through the console through `window.someproperty` or/and from SingleFile context menu when it detects its files. (e.g., `open live version`.)
- A node app that incorporates [puppeteer](https://github.com/puppeteer/puppeteer) and downloads SingleFiles headlessly and is capable of updating a directory of SingleFiles (overwriting or to a new subdirectory).

**I've considered**
Opening the file, googling something unique from the markup and rerunning SingleFile.

**Comment by gildas-lormeau** [comment]
- Extracting the URL is today a bit more complicated than your proposal but it's doable. The following code allows you to get the URL of the page: `document.documentElement.childNodes[0].textContent.split("\n")[2].split("url:")[1].trim()`. I agree it could be nicer to get it via a property in the `window` object for example.
- The Node application using Puppeteer (and Selenium, jsdom) already exists, cf. https://github.com/gildas-lormeau/SingleFile/tree/master/cli. However you may have to adapt the code for your needs.

**Comment by alivefromupstairs** [comment]
**Consider:**
- Adding the cli README to the main README somewhere.
- Offering an npm module that could be installed globally and a docker hub container.
  `npm i -g single-file` `docker pull single-file`.
- Changing the `git clone` command in dockerfile to `git clone --depth 1` (it was taking a really long time to download; this repo is 323.95MB in size).
https://github.com/gildas-lormeau/SingleFile/blob/b84d898d883cd2e022e34bc5e1492436066027fa/cli/dockerfile#L5
- having a `--filename-template` by default.

**Question:** how to use `--filename-template` with docker?
What is suggested is piping the output into a file
```fish
docker run singlefile "https://www.wikipedia.org" > wikipedia.html
```
Running
```fish
docker run singlefile "https://www.wikipedia.org" --filename-template '{page-title}.html'
``` 
executes without error, but the output file is nowhere to be found.

**Comment by alivefromupstairs** [comment]
also, do you have any suggestions on how to scrape my local html files for `document.documentElement.childNodes[0].textContent.split("\n")[2].split("url:")[1].trim()` easily into a file to later `xargs` it into `singlefile`? Last time I scraped using `beautifulsoup` was 2 years ago. I am on Arch Linux.

**Comment by gildas-lormeau** [comment]
- The existence of the CLI is mentioned in the description, the introduction and there is chapter about it in the README of SingleFile which gives a link to the README of the CLI.
- Historically SingleFile is an extension, that's why the code of SingleFile is not packaged as a Node module. That's also why it's not available on NPM. That may change in the future but it needs some work to refactor the project. For example, it might make no sense to publish on NPM the code related to the extension.
- Thank you for the suggestion about using `--depth`, I agree with you and I'll update the documentation
- The `--filename-template` can be used outside Docker. I'm not a Docker specialist but AFAIK, you're not really supposed to browse its filesystem. That's why it's recommended to use the pipe operator. If you want to use the `--filename-template` option with the Docker image, I think you should be able to find the generated file by browsing the filesystem of the Docker image (cf. https://stackoverflow.com/questions/20813486/exploring-docker-containers-file-system for example).
- I think you could use a Regexp to parse your local HTML files. That would be the most efficient and the simplest solution from my point of view. This regular expression should allow you to extract URLs from the text of the saved pages: `/\<!--\n Page saved with SingleFile \n url:(.*) \n/`.

**Comment by gildas-lormeau** [comment]
@alivefromupstairs Is this issue fixed?

**Comment by gildas-lormeau** [comment]
Great! :)

**Comment by alivefromupstairs** [comment]
@gildas-lormeau I would ask what did you use to filter with that regex:
> /\<!--\n Page saved with SingleFile \n url:(.*) \n/.

Gnu's `grep` does not use that flavor.

**Comment by gildas-lormeau** [comment]
Indeed, try this instead:

`grep -Pzo "<\!--\n Page saved with SingleFile \n url: \K(.*)\n"  *.html`
