### ISSUE TITLE
Lighten more saved pages?

### ISSUE THREAD

**Issue by user0022** [gildas-lormeau/SingleFile#364]
Hello! To me and according to what I've read from other users, size reducing of pages is greatly appreciated!

But are minification or removals at their best? Maybe they are but I've had the impression to see that it can be yet a bit improved! (?).
I'm not a coder I just know a few CSS and HTML, but I've opened some SF pages in a text editor (Leapad or Gedit...) and there seemed to be yet things to do or to do more:
- Indentations removal.
  They should be already all removed by the corresponding option? In "HTML content":
  Option: compress HTML content   [x]
  (i) Check this option to remove all HTML comments and unneeded tags, **spaces**, quotes and **whitespace characters**. (...)
  But I've seen some.
  A remark: shouldn't it be the word "minify" instead of "compress"? (Or lighten, shrink, reduce, shorten, or else, if minify is too technical). Compressing being what SingleFileZ does? But maybe even if it's true it's not so important.
- Line breaks -> I've seen many e. g. in tables, with `<tr>` or`<td>`.
- Color codes with "double digit" are said reducable from 6 to 3, e. g. `#112244` can be `#124`.
- Metadata removal? Mostly are present in certain pictures? Maybe already done but I mention it because I didn't see it indicated.

**
The first 3 things were present in this page for example: https://distrowatch.com/, when saved and opened in a text editor.

I made a small removal test at my low level, by replacing with Ctrl+H in the editor.
At first, size was: 1,5 Mo (1 483 349 bytes).
Then I made: `>(+line break, + one space)<` replaced by `><`.
And: `>(+line break)` replaced by `>`.
And the size became: 1,5 Mo (1 479 740 bytes).
Which is a drop of only 3609 bytes that makes 0,24%, but the page looked still the same, only some movings of 1/2/3mm.

I saw the same kind of line breaks and indentations in another example:
https://askubuntu.com/questions/15832/how-do-i-get-the-cpu-temperature

**
If these shrinkages are OK to apply, there would maybe stay yet other things to do without altering page?
A small question: did you pick what to reduce yourself, or did you use an existing software? Typing "minif" in Synaptic (free software in Debian etc) sent a small list with minifiers for HTML, CSS, or Javascript.
A crazy idea from me (or simply a bad or trivial idea): maybe even code rewriting! Detect and replace bad and/or heavy code, which must exist maybe especially in old pages, by better/lighter/faster one. Is it possible to do automatically? And legal? But it could be too heavy too.

**Comment by gildas-lormeau** [comment]
Removing all unneeded whitespaces must be done carefully. Indeed, you cannot remove all of them because you might break the layout of the page. Here is below a script that you can run in the developer tools to see the issue.
```
const replacedNodes = new Map();
const treeWalker = document.createTreeWalker(document, NodeFilter.SHOW_TEXT);
while (treeWalker.nextNode()) {
    const textValue = treeWalker.currentNode.textContent.trim();
    const textContent = document.createTextNode(textValue);
    replacedNodes.set(treeWalker.currentNode, textContent);
}
Array.from(replacedNodes.keys()).forEach(originalNode => originalNode.parentNode.replaceChild(replacedNodes.get(originalNode), originalNode));
```
This code removes all the whitespaces (e.g. tabs, newline, spaces) before and after any text found in the page. It also removes text containing whitespaces only. If you run it on the current page, for example, you'll see that some significant spaces are removed and this impacts the readability of the page. So, today, SingleFile is very prudent and try to avoid this issue as much as possible. That's why you're seeing remaining whitespaces. Maybe there's some room for optimization but it will be almost negligible.

Regarding the compression of color codes. I think the option "compress CSS" should do the job most of the time. It's disabled by default now because I consider it consumes too much CPU.

SingleFile doesn't remove metadata because they can provide useful data.

I've written almost all the code related to these optimizations because such code did not really exist and wasn't working as I wanted. For example, SingleFile can remove unneeded quotes and optional tags in the HTML. I didn't know any library that I could use for this so I wrote the code. The same applies for CSS optimizations. I had to code a library in order to compute what in the CSS is really used, and which fonts can be safely removed. These optimizations are generally very efficient. On the current page, they can remove almost 90% of the content.

**Comment by user0022** [comment]
OK thank you and excuse for delay!

I answer to myself: probably I was talking a bit nonsense, the "compress" word is maybe correct, in a general sense, maybe SingleFileZ "archives", or......  sorry well I don't know.

Thanks for the copy of the script, I've watched (in Firefox) in Tool > Web Developper > Inspector, Console, etc, but I couldn't find where to put it, neither know I the basic grammar of script to insert it, to make the test. As I said, I only know a few CSS and HTML :/. Anyway I trust you, and now I see that apparently you didn't do this aspect of the extension like "nevermind", but made it already with care, so my doubt of possible rather easy improvements would be wrong.

Nevertheless maybe I would still vote yes for metadata removal option? By thinking that they are a bit "technical", and also may content thumbnails which can be some heavy (but which is already removed maybe with option **Images > remove images for alternative screen resolutions [x]**). And maybe big majority of users don't mind for them, or if they care for them, they know it, and then don't check the option. But well I'm very possibly wrong, for I don't know all this pictures stuff, and they could be more useful than I thought!

It's true that I should use SingleFileZ instead if I like so much size reducing, I have both but I rather use SingleFile for good or bad reasons, but probably I'm gonna use SFZ more.
Anyway if some more reducing would have been possible also in SF why not I think!

**Comment by gildas-lormeau** [comment]
Actually, I used the word "compress" instead of "minify" because I think it was easier to understand for non-technical people. I might be wrong though.

You have indeed to paste the code in the "Console" tab of the developer tools, after the chevron icon, and press enter to run it.

Note that removing the metadata will save in most cases less than 1KB of data. They usually contains only small texts and URLs (which are not processed by SingleFile).

**Comment by gildas-lormeau** [comment]
I'm closing this issue because I think a lot of efforts are done to lighten the page as much as possible without consuming too much CPU. However, I know it's important to optimize the weight of the file (with the default settings) and that's something I try to improve constantly.
