### ISSUE TITLE
"save selected tabs"

### ISSUE THREAD

**Issue by labyrinth-to-solve** [gildas-lormeau/SingleFile#365]
When I try to use "save selected tabs" only the first tab is saved.
I am using the Sidebery add-on.
Is there a conflict between SingleFile and Sidebery add-ons?
SingleFile 1.17.4, Firefox 73.0 (64 bit), Ubuntu 18.04.4

**Comment by gildas-lormeau** [comment]
Indeed, I did a test with the add-on Sidebery and I confirm that if you try to select tabs (with Shift+left click, for example) in the side panel, tabs are not selected in the tabs bar of Firefox. That's why it does not work. Ideally, Sidebery should call [`browser.tabs.update`](https://developer.mozilla.org/docs/Mozilla/Add-ons/WebExtensions/API/tabs/update) with the property `highlighted` set to `true` to select tabs natively and be compatible with SingleFile. Note that it still work if you select tabs via the tabs bar, so the extensions are not conflicting each other.

**Comment by gildas-lormeau** [comment]
FYI, I did the same kind of test with Tree Style Tab and it worked fine. So, I'm tempted to say it's a bug in Sidebery.

**Comment by labyrinth-to-solve** [comment]
Thanks for your answer. I informed Sidebery about your comment - https://github.com/mbnuqw/sidebery/issues/142

**Comment by mbnuqw** [comment]
To resolve this conflict, you need to enable the option "Highlight native tabs (in top horizontal bar) along with tabs in sidebar" in "Tabs" section.

**Comment by gildas-lormeau** [comment]
Thank you @mbnuqw. I did a quick test and I confirm that enabling the option "Highlight native tabs" fixes the issue on my end.

**Comment by gildas-lormeau** [comment]
@labyrinth-to-solve I'm closing this issue because it's solved. Feel free to reopen it if necessary.
