### ISSUE TITLE
Request to add a function

### ISSUE THREAD

**Issue by currencyporter** [gildas-lormeau/SingleFile#366]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
The webpage can be saved with the information of the source URL. Thank you
**Describe alternatives you've considered (optional)**

**Additional context (optional)**

**Comment by gildas-lormeau** [comment]
The source URL can be found in the infobar. It's an icon that is displayed at the top right of the saved page. When you click on it, it gives you the saved date and a link to the source URL. If you're using a Chromium-based browser, make sure the option "Allow access to file URLs" is enabled in the extension page (chrome://extensions/?id=mpiodijhokgodhhofbcjdecpffjipkle) otherwise the icon won't be displayed. If you want to display that icon even though SingleFile is not installed in the browser you're using to view saved pages, please enable the option "HTML content > include the infobar in the saved page" in the options page of SingleFile.

**Comment by gildas-lormeau** [comment]
@currencyporter I'm closing this issue since the source URL is indeed embedded in saved pages. Feel free to reopen it if necessary.
