### ISSUE TITLE
Saving several level deep

### ISSUE THREAD

**Issue by cherwally** [gildas-lormeau/SingleFile#371]
**Feature request:**
I need to save up some Photoshop tutorials, 
but most of the time they have 1-3 levels deep links for extra info or next page of the tutorial.

**Describe the solution you'd like**
Can we have this option added to save several layers deep please?

**Alternatives I've considered:**
The only software i have found doing this, 
but the interface is is very complex and unfriendly for a normal user.
Otherwise it does same as many levels deep you set!
But i do prefer as a solution a Firefox plugin instead of a standalone software.
https://www.httrack.com/page/2/en/index.html

**Comment by gildas-lormeau** [comment]
Since crawling a website is a bit boring and can take a lot of time, I was thinking it would be more appropriate to implement this feature when [using SingleFile from the command line interface](https://github.com/gildas-lormeau/SingleFile/tree/master/cli) (like HTTrack). It's also a bit hard for me to imagine how to integrate this feature in SingleFile without making the extension too complex.
Would you still be interested by this feature if I implemented it that way?

**Comment by cherwally** [comment]
**HHTrak already looks very complex to me.
I was aiming at simplicity...
Like...adding only a small popup on icon click asking how many levels to crawl.
Never been a fan of command line applications**

**Comment by cherwally** [comment]
**I accidentally closed the thread...
that button "Close and comment" is a bit confusing...**

**Comment by gildas-lormeau** [comment]
No problem for the accidental click. It happens often on Github ;)

I keep the issue open. I think I need to take my time to see how this feature could be integrated in SingleFile without having an impact on the current user experience. 

The other problem for me is the notion of "deepness". I need to see how HTTrack handles it. The problem is that the folder you see in the URL do not necessarily correspond to the deepness of the page on the site. For example, a e-commerce website could use URLs like https://www.example.com/category/<id> for categories and https://www.example.com/product/<id>for the products whereas, as a user, you consider that product pages are deeper than category pages. I hope I'm clear :p

**Comment by cherwally** [comment]
**On my logic, I'll say that 1 lever deep is any landing page/photo/link by clicking ONCE.
2 levels deep should be also ability to browse in any direction page/photo/link
by clicking 2 times (not consecutive, just 2 different clicks)
And website real hierarchy should not be taken in consideration.
I am far from reaching you tech level but i do my best to help ;)**

**Comment by gildas-lormeau** [comment]
I agree with you I think. Maybe I would call this the perimeter instead of the level of deepness though.

**Comment by gildas-lormeau** [comment]
I added some options that allow to crawl a website automatically.
- pass `--crawl-links=true` to crawl URL(s)
- pass `--crawl-inner-links-only=false` to crawl all the links whether they are from the same domain or not
 - pass `--crawl-max-depth=<number>' where `<number>` is the max depth when crawling links
 - pass `url-rewrite-rules="<rewrite rules>"` where `<rewrite rules>` is a rule to transform URLs before capturing them. For example `"^(.*)\\?.*$ $1"` will remove query parameters

**Comment by boweden** [comment]
Thanks for this.  what are the default values for the new options if they are not explicitly mentioned?

**Comment by gildas-lormeau** [comment]
It should be mentioned when you use `--help`, I guess. The default values are:
 - `--crawl-links=false`
 - `--crawl-inner-links-only=true`
 - `--crawl-max-depth=1`
 - `--url-rewrite-rules` is empty by default

**Comment by gildas-lormeau** [comment]
Note that you could also use the option `--urls-file` to crawl multiple sites.

**Comment by gildas-lormeau** [comment]
@boweden Note that there is bug right now, you must pass `--browser-debug=true` otherwise it won't work.

**Comment by gildas-lormeau** [comment]
And it's fixed, `--browser-debug=true` is not necessary anymore.

**Comment by boweden** [comment]
I tried setting up SingleFile CLI, but unfortunately i've been having problems just getting it up and running, let alone testing this new feature. Maybe the CLI way is a bit too sophisticated for me.


I installed via scoop, then installed git, then installed nodejs, then npm.

Then tried installing puppeteer-firefox.  I get the following error message:

Error:  Failed to download Firefox rv0.0.1!
Error: Download failed: server returned code 404...

<...>

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! puppeteer-firefox@0.5.1 install:  `node install.js`
npm ERR! Exit status 1
npm ERR! Failed at the puppeteer-firefox@0.5.1 install script.



So I tried installing selenium-webdriver instead. Got it installed, I think (didn't get any error messages).  Set back-end to webdriver-gecko. I get this message:

(node:7880) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'trim' of undefined
	at rewriteURL (..\path\to\SingleFile\cli\single-file:241:12)
	at ..\path\to\SingleFile\cli\single-file:196:19

<a couple more UnhandledPromiseRejectionWarnings>


Looks like the selenium webdriver component wasn't set in the PATH variable. So I tried --web-driver-executable-path and manually pointed it out to geckodriver.exe.  This time I get:

(node:7996) UnhandledPromiseRejectionWarning: Error: Could not find browser revision 737027. Run "npm install" or "yarn install" to download a browser binary.
<...>



I give up. I'm going to take a nap. I'll try again later.  I'd really like to avoid downloading Chrome just to use this feature, but if I have no choice I suppose I might have to start using it.

**Comment by gildas-lormeau** [comment]
@boweden I confirm `pupeteer-firefox` is broken. Google stopped to support it. I removed the corresponding instructions. If you want to use Firefox, use `webdriver-gecko` as backend.

**Comment by gildas-lormeau** [comment]
I just fixed the issue related to `--web-driver-executable-path`.

**Comment by gildas-lormeau** [comment]
I added the option `--crawl-replace-urls` which is set to `true` by default. When set to `true` the URLs of saved pages will be replaced with relative paths of saved pages on the filesystem.

**Comment by boweden** [comment]
Thank you for your continued assistance. I realized after I installed nodejs via scoop (i.e. "scoop install nodejs"), I could also install the geckodriver via scoop (i.e. "scoop install geckodriver") and not worry about setting any PATH variables.

Now that I have it working, I would like to give some feedback. 

I tried out this feature on the webpage example I mentioned earlier:

`single-file https://gamefaqs.gamespot.com/pc/564462-a-mind-forever-voyaging/faqs/74934 --crawl-inner-links-only=true --crawl-max-depth=3`

First, it still does not seem to capture the inner links?  I only see page0 (i.e. the main page).  I would greatly appreciate it if you would suggest the options that you would use here if you were to save this page (just the inner links only).

Secondly, this headless browser method is unfortunately slow. Very slow compared to the "wget method".  But more importantly, when you open the saved page created by the geckodriver's headless browser, it makes the existing tabs unresponsive if you have your browser already open. You are stuck in the tab you are looking at, and cannot switch to the other tabs.

Is there any particular reason why you don't want to use the "wget method"? It's super fast and it replicates everything *exactly* as the original site.  The only thing it doesn't do is put it all in a *single* container file...

**Comment by gildas-lormeau** [comment]
I'm sorry if you're not satisfied with SingleFile. AFAIK, wget is not a browser.

**Comment by boweden** [comment]
I'm the one that should apologize. Re-reading my previous response, I realize I come across like a demanding, ignorant child that wants things to be done his way.  I should've known you have technical reasons for doing it the way you do.  

I'm always grateful for this fantastic tool that you've made with your valuable time and for choosing to share it with the world for free. Thank you again.

**Comment by gildas-lormeau** [comment]
@boweden Your example did not work because you did not set `--crawl-links` to `true`. Otherwise `--crawl-inner-links-only` has no effect.

**Comment by boweden** [comment]
sorry, I think I must've forgot to mention that I had `--crawl-links` to `true`.  But just to be sure, I reinstalled and retried this procedure again:

single-file https://gamefaqs.gamespot.com/pc/564462-a-mind-forever-voyaging/faqs/74934 --back-end=webdriver-gecko --crawl-links=true --crawl-inner-links-only=true --crawl-max-depth=3

But again, the inner links on the main page that point to "Next Page" and "Last Page" are `https://` links, not local `file:///` links.  

Maybe I misunderstood something here, but would this feature be more suitable for SingleFileZ, since SingleFileZ seems to preserve the directory structure accurately inside its container, therefore making the inner links be easily accessible ?

**Comment by gildas-lormeau** [comment]
Running `single-file https://gamefaqs.gamespot.com/pc/564462-a-mind-forever-voyaging/faqs/74934 --browser-wait-until=load --back-end=webdriver-gecko --web-driver-executable-path=...geckodriver.exe --browser-executable-path=...firefox --crawl-inner-links-only=true --crawl-links=true --crawl-max-depth=1 --crawl-replace-urls=true` works on my end. The only issue is that `--browser-wait-until=load` web webdriver-gecko is mandatory, I need to see why.

However, since there are more than 100 inner links, I interrupted the script. Since I interrupted the script the switch `--crawl-replace-urls=true` (that you forgot in your example) has been ignored. It has been ignored because it's impossible to determine in advance what will be the file:/// URI of a inner link. This task is done when all the pages have been captured.

Please make sure the code of SingleFile is up to date and run in the cli folder `npm update`. then yiu can run for example `single-file https://goldenhourapp.com/ --back-end=webdriver-gecko --browser-wait-until=load --web-driver-executable-path=...geckodriver --browser-executable-path=...firefox --crawl-inner-links-only=true --crawl-links=true --crawl-max-depth=1 --crawl-replace-urls=true`. It should save 4 pages that are linked together.

**Comment by boweden** [comment]
Thank you very much. You are right that I forgot both --crawl-replace-urls=true and --browser-wait-until=load

It certainly works now, especially using your goldenhourapp.com example.  In my situation, I let the script run even though there were more than 100 links like you said.  But after about 45 min or so, there were so many firefox processes that I had no choice but to end the script since my computer was freezing up.  I guess a very powerful PC is needed for this script since web pages in general, have quite a bit of links.  

And also, since the filenames were getting very long, I suspect there will be a situation where filepath length will exceed the limit imposed by the operating system and might crash the script.  Perhaps SingeFileZ's directory-file naming structure is probably needed here.  Still, the bigger problem I guess is that too many links will create too many firefox processes potentially leading to a slowdown/crash.

**Comment by gildas-lormeau** [comment]
I'll try to fix these issues with Firefox. Today, SingleFile works best when using Chrome with Puppeteer.

Filenames are truncated and there's an option to configure the maximum length, like in the extension.

**Comment by 07416** [comment]
Is this feature request about "outlinks", i.e. all links on the page which point to other webpages?
