### ISSUE TITLE
'Where from' metadada

### ISSUE THREAD

**Issue by qwerty-keys** [gildas-lormeau/SingleFile#388]
Firstly, thank you for creating such an amazing extension. It is a great tool for online research.

SingleFile already has extended metadata injection for the _Where from_ attribute (com.apple.metadata:kMDItemWhereFroms) but it points to something like this: 

_blob:moz-extension://8893235a-34fc-5747-9819-1db4e62e7074/c15244a1-4cfb-f649-bac3-5f2d4200647a_

It would be nice to have the actual **url** of the web page instead. I use DEVONthink a lot and SingleFile to import .html files but first I have to use **xattred** (another great tool) to inject the url into the each html file. That way, the original url is shown on DEVONthink's address bar and file properties tab. Below are some screenshots for reference:

[https://mega.nz/folder/aAAkGaLL#HGsJKmZ6CSCha85r_7K8UA](url)

That feature alone would put Instapaper and Pocket out of business, imho :-)

Thank you and stay safe!

qk

**Comment by gildas-lormeau** [comment]
I don't know anything about that metadata. Actually, I don't have any Apple machine. However, I suspect disabling "misc > save pages in background" might help to fix this issue. Can you please do this test?

**Comment by qwerty-keys** [comment]
Thank you for that prompt reply... I did that and now the url is there... But there is a 'blob' text before the actual url as in _**blob:https://www.bbc.com**_. Is there a way to remove that 'blob' part?  Devonthink won't recognize the url with that part. Thank you once more!

**Comment by gildas-lormeau** [comment]
You're welcome :)

Unfortunately, I think this will be more complicated. There is one thing that I would like to test though. If that's okay for you, I'll propose you to install a custom build of SingleFile manually and do the test. I think I should be able to deliver this custom build in the coming hours.

Out of curiosity, do you see the same issue if you use SingleFile with an alternative browser, i.e. Chrome or Firefox?

**Comment by qwerty-keys** [comment]
Absolutely, I'm in (for the test.) I might not be around for a few hours but I'll be checking this post for the custom build.  I mostly use Firefox. I also use Microsoft Edge, Chromium and Opera. I have SingleFile installed in all of them.

**Comment by gildas-lormeau** [comment]
Thank you for your help. So, you confirm you see the exact same issue in all these browsers today?

**Comment by qwerty-keys** [comment]
I'll do that on macos and in Firefox and edge for windows as well... later tonight...  thank you

**Comment by gildas-lormeau** [comment]
No problem. Here is the custom build, you can install it by following the procedure described [here](https://github.com/gildas-lormeau/SingleFile#install)

[singlefile.zip](https://github.com/gildas-lormeau/SingleFile/files/4458046/singlefile.zip)

**Comment by qwerty-keys** [comment]
Hi Gildas. Finally I was able to run tests on Firefox Dev Ed for mac and windows with the build you sent me. Only Firefox for macOS creates the _**Where from**_ metadata. I'm including here a zip with html files from various browsers I used.  

[singlefile-tests.zip](https://github.com/gildas-lormeau/SingleFile/files/4458984/singlefile-tests.zip)

Also, (at least for me) the info bar at the top right only appears in Firefox for macOS and is not present in any other browse.  I disabled all other extensions and adblockers in my browsers and still the info bar wouldn't show. In Firefox macOS I use **_{url-href}_** and works very well. 

I've been using SingleFile for years in conjunction with **Open Original for SingleFile** to have access to source urls, but that extension is no longer updated and doesn't work anymore. Maybe the Info bar is the way to go. I volunteer to test future updates. 

Thank you once more for your attention to this matter and stay safe!

qk

**Comment by gildas-lormeau** [comment]
Thank you @qwerty-keys for the detailed feedback. It's too bad the custom build did not help. Currently, I do not have any other idea on how to fix or circumvent this issue.

Since the result defers depending on the browser you're using, I'm tempting to say the current issue is a bug in the browser(s). It would be interesting to know the result of the same tests with the regular version of SingleFile though. I guess only Firefox will set the value.

In Chromium-based browsers, make sure the option "Allow access to file URLs" is enabled in the details page of the extension (e.g. chrome://extensions/?id=mpiodijhokgodhhofbcjdecpffjipkle for Chrome) otherwise the infobar won't be displayed. Alternatively, there's an option in SingleFile to embed the infobar in the file, cf. "HTML content > include the infobar in the saved page".

I did not know "Open Original for SingleFile" wasn't working anymore. I'm not the author but it might be my fault, I'll do some tests to see why it's broken.

Stay safe too!

**Comment by qwerty-keys** [comment]
Ok, now the info bar works lie a charm in all browsers!  Thanks so much for your time and keep it up!

**Comment by gildas-lormeau** [comment]
You're welcome. I'm closing the issue because I cannot do anything to fix the "blob" bug in the "Where" metadata when the option "Misc. > save pages in background" is disabled. I would maybe recommend you to create an issue on https://bugzilla.mozilla.org, I found nothing related to it, cf. https://bugzilla.mozilla.org/buglist.cgi?quicksearch=where+blob

**Comment by gildas-lormeau** [comment]
I added the hidden option `useLegacyCommentHeader` that you can enable by replacing its default value (`false`) with `true`. The extension "Open Original for SingleFile" will work when this option is set to `true`. The procedure to set hidden options is described here: https://github.com/gildas-lormeau/SingleFile/wiki/Hidden-options.

The version implementing this feature (1.17.35+) will be available in approximately one week on the store of Chrome.

**Comment by qwerty-keys** [comment]
Gildas, you're the man 😊
