### ISSUE TITLE
Tooltips

### ISSUE THREAD

**Issue by alekssmitt** [gildas-lormeau/SingleFile#401]
I tried to save the article with tooltips, but without much success.
Is there any way to “fix it”?
Like, for example, on the page where I was
https://www.urbandictionary.com/define.php?term=doof

**Comment by gildas-lormeau** [comment]
On this particular website, it's impossible. In fact, each time you display a tooltip, a request is sent to their server in order to get the content of the tooltip.

Generally speaking, in such cases you can try to disable the option "Other resources > remove scripts". If it does not work, you can also keep it disabled and enable the option "Misc. > save raw page".

**Comment by alekssmitt** [comment]
Yes, I know this, and in the past I have saved several pages with tooltips.
Never mind, I was just hoping this problem could be solved as java-script and this app-extension evolve

**Comment by gildas-lormeau** [comment]
No, unfortunately. This kind of problem is difficult, if not impossible, to solve.

**Comment by alekssmitt** [comment]
I understand. When I wrote 
> I was just hoping this problem could be solved

I meant that some ideas may appear in the future. And I really hope that they will be. In the meantime, let me close this question.

**Comment by gildas-lormeau** [comment]
Web bundles are more or less supposed to solve these kind of problems, you can find more info about this format here: https://web.dev/web-bundles/

**Comment by alekssmitt** [comment]
Maybe in some distant future... All human beings, including me, opted to ease their lives, not complicate things. I'm quite happy with your app, even if it not full-fledged yet.
