### ISSUE TITLE
License

### ISSUE THREAD

**Issue by chaseadam** [gildas-lormeau/SingleFile#41]
Just discovered this plugin and find it very useful. Thanks for maintaining it!
Can you post a clear license?

**Comment by fatso83** [comment]
@gildas-lormeau This is preventing people from fixing your code, which is currently broken, and/or adding features to it. It would be helpful to explicitly allow people to modify it, as long as you are mentioned, or similar.

For anyone that might wonder:
--- 
>Say that a public github project does not have a license specified. Can I use that code in my own code?

* **No**, if software is published without a license granting you rights to distribute that software, then in **[most countries][1]** you have **no rights** to distribute that software.

Just because it is available for download doesn't mean that it is in the [public domain][2]. In fact it is protected by the [WIPO Copyright Treaty][4] and thus the [Berne Convention][3] even if it is downloadable and even if it doesn't include a copyright notice - copyright is attached automatically on creation. 

>Can I use any open source license?

* **No**, any license you try to attach to that code would be void. Since you do not own copyright on the material, you cannot assign rights over that code to others.

Note that it can be legal to download without being legal to distribute it further. The fact that code has been uploaded to github [gives you the rights listed in the github terms and conditions](https://help.github.com/articles/github-terms-of-service/#5-license-grant-to-other-users) but no more. In other words, you can view and fork (copy/download) a github repository, but you cannot distribute that content without a licence which grants you further rights.

  [1]: http://en.wikipedia.org/wiki/World_Intellectual_Property_Organization
  [2]: http://en.wikipedia.org/wiki/Public_domain
  [3]: http://en.wikipedia.org/wiki/International_copyright_agreements#Berne_Convention
  [4]: http://en.wikipedia.org/wiki/WIPO_Copyright_Treaty

---

Ref https://stackoverflow.com/a/7796464/200987

**Comment by gildas-lormeau** [comment]
The licence is present in each JS file.
