### ISSUE TITLE
The disabled option to minify CSS stylesheets does not work.

### ISSUE THREAD

**Issue by XX-J** [gildas-lormeau/SingleFile#411]
**Describe the bug**
The disabled option to minify CSS stylesheets does not work.

**To Reproduce**
1. Go to settings.
2. Disable option, that minify CSS stylesheets.
3. Save ["Example"](https://github.com/gildas-lormeau/SingleFile/files/4613890/Example.zip) page.
4. Compare source code of "Example" and "Result" page.

**Expected behavior**
CSS stylesheets are not minifying.

**<details><summary>Screenshots:**</summary>

 Settings:

![2020 05 11-7](https://user-images.githubusercontent.com/17948007/81647757-3960a000-9436-11ea-958b-c05e06ec6ca4.png)
----------
 Source page:

![2020 05 12-2](https://user-images.githubusercontent.com/17948007/81647810-4da49d00-9436-11ea-8c34-002cb811065b.png)
----------
 Saved page:

![2020 05 12-3](https://user-images.githubusercontent.com/17948007/81647823-5301e780-9436-11ea-94c0-249135bc53c6.png)
</details>

**Environment**
 - OS: Win7 SP1 x64 Ru
 - Browser: Mozilla Firefox v53.0.3 and Google Chrome v75
 - SingleFile: v1.17.41

**Additional context**
And also I would like SingleFile don't add additional closing HTML tags and other information, which is not initially included in the original HTML page.
**<details><summary>Screenshot:**</summary>

 Additional unwanted information:

![2020 05 12-4](https://user-images.githubusercontent.com/17948007/81650292-55fed700-943a-11ea-98a9-343b2982c52a.png)
</details>

**Comment by gildas-lormeau** [comment]
I did some tests and I confirm the option *does* work. However, the minification implementation is maybe not as sophisticated as you think. FYI, this implementation is based on a fork of the CSS compressor of [YUI Compressor](https://yui.github.io/yuicompressor/css.html) with some code disabled because of performance issues. In your example there's nothing this implementation can minify actually. However, if you replaced any color with for example "#000080", you'll see this color will be replaced with "navy". In fact, the compressor is a bit old and maybe obsolete. That's why the option is disabled by default. Could you describe what you were expecting as result?

**Comment by XX-J** [comment]
CSS stylesheets minify despite disabled option.

> Could you describe what you were expecting as result?

 I don't want (or on option based) what SingleFile is do:

1. Removes spaces and line breaks in CSS and HTML;
2. Adding unnecessary HTML tags;
3. Adding additional unnecessary information in HTML document, like this:

![2020 05 12-4](https://user-images.githubusercontent.com/17948007/81650292-55fed700-943a-11ea-98a9-343b2982c52a.png)

**Comment by gildas-lormeau** [comment]
Thank you for the additional info. Today, it's impossible with SingleFile to get the CSS contents with spaces and comments preserved. This is due to the fact that it uses a CSS parser that removes them. This is a drawback of the parser and this cannot be easily fixed.

Today, the HTML comment "Page saved with SingleFile" is always inserted in the page. I might add an option to remove it in the future.

You can remove the <link> tag you highlighted by disabling the hidden option `insertCanonicalLink`. You can do this by exporting the settings of SingleFile, opening the file in a text editor, replacing `insertCanonicalLink: true` with `insertCanonicalLink: false`, and importing the modified settings.

The unnecessary tags are necessary actually. They are there to make your HTML page compliant with the specification. For example, [the specification](https://html.spec.whatwg.org/multipage/syntax.html#optional-tags) says:
- "A head element's start tag may be omitted if the element is empty, or if the first thing inside the head element is an element."
In your page, the head element is not empty and the first thing inside is an ASCII whitespace (which is U+0009 TAB, U+000A LF, U+000C FF, U+000D CR, or U+0020 SPACE, see https://infra.spec.whatwg.org/#ascii-whitespace).

- "A head element's end tag may be omitted if the head element is not immediately followed by ASCII whitespace or a comment."
In your page, the head element is immediately followed by ASCII whitespace.

**Comment by gildas-lormeau** [comment]
Sorry, I'm wrong. Setting `insertCanonicalLink` to `false` won't work.

**Comment by XX-J** [comment]
> ...the <link> won't be inserted if the page has been saved from the filesystem.

 Make same for comment "Page saved with SingleFile", please.
__________

 For what needed "link Canonical" and "Page saved with SingleFile" comment, if both contain identical URL of saved page? May be leave only one, "Page saved with SingleFile" comment?

**Comment by gildas-lormeau** [comment]
The canonical URL is not necessarily the same. If it was already defined, it's kept as is.

**Comment by gildas-lormeau** [comment]
I'm closing this issue since I made the changes I could. However, I'm not sure SingleFile is the tool you need. There is always a risk it will reformat the page.
