### ISSUE TITLE
page cannot be saved - polizei.sachsen.de

### ISSUE THREAD

**Issue by DeVIL-I386** [gildas-lormeau/SingleFile#415]
This page cannot be saved:

https://www.polizei.sachsen.de/de/

As soon as you want to save it, it will be reloaded shortly afterwards, but nothing will be saved.
No error message is displayed.

Firefox 76.0.1
SingleFile 1.17.43
Windows 10 64-bit

Test was also performed in private mode.

**Comment by gildas-lormeau** [comment]
Thank you for having reported this issue. It's due to the option "Images > save deferred images". On this website, you zoom in/out the page, it reloads itself. This behavior is the cause of the bug. Disabling this option allows you to save the page.

**Comment by DeVIL-I386** [comment]
Und wo liegt hier das Problem?

https://www.polizei.sachsen.de/de/MI_2020_72491.htm

**Comment by gildas-lormeau** [comment]
You mean the background image missing in the header (and the menu)? This is another issue that I did not notice... 
This is due to a problem when determining which background to apply. The stylesheet is a bit complicated and SingleFile does not select the correct value for the `background` property. I'll try to see if I can fix it.

**Comment by DeVIL-I386** [comment]
Well, that's another matter. My problem is solved. Thanks for the help.
