### ISSUE TITLE
collapsed content seems not saved? 折叠的网页内容不能被保存

### ISSUE THREAD

**Issue by Vincendovich** [gildas-lormeau/SingleFile#438]
Hi, there,

**Is your feature request related to a problem? Please describe.** --yes!

collapsed content seems not saved, for instance, this website, https://www.lucigen.com/FAQ-quickextract-plant-extraction-solution.html, the content which shows after clicking the plus symbols is not available in the saved html.

**Describe the solution you'd like**

the collapsed content can be saved as well.

**Describe alternatives you've considered (optional)**

n.a.

**Additional context (optional)**

n.a.

**Comment by gildas-lormeau** [comment]
This issue is documented in the FAQ here: https://github.com/gildas-lormeau/SingleFile/blob/master/faq.md#why-dont-interactive-elements-like-folding-titles-dynamic-maps-or-carousels-work-properly-in-saved-pages. For this particular website, disabling "Other resources > remove scripts" almost works. Unfortunately, a modal popup blocks the content of the page.

**Comment by Vincendovich** [comment]
many thanks, gildas-lormeau

**Comment by gildas-lormeau** [comment]
You're welcome :)

**Comment by gildas-lormeau** [comment]
I'm closing the issue, feel free to reopen it or comment it if necessary.
