### ISSUE TITLE
Option "Always ask you where to save files" ignored

### ISSUE THREAD

**Issue by zwn** [gildas-lormeau/SingleFile#485]
Even though the option "Always ask you where to save files" is set in Firefox preferences, the page is saved into a directory that is set in the (disabled) option "Save files to".

1.  Click "Always ask you where to save file"
2.  Switch to a different tab and click on "SingleFile" icon in the toolbar
3.  The page is saved in the directory shown in the disabled option "Save files to"

**Expected behavior**
A dialog asking where to save the file is presented.

**Environment**
 - OS: Ubuntu 18.04.5 LTS
 - Browser: Firefox
 - Version: 80

**Comment by gildas-lormeau** [comment]
Please enable the seeting `File name > open the "Save as" dialog to confirm the file name` in the options page of SingleFile.

**Comment by zwn** [comment]
Oh, yes - with that option set I get the dialog, thanks.

So, that it does not respect the global option is not a bug but an intentional design decision? If that is the case we can close this issue.

**Comment by gildas-lormeau** [comment]
You're welcome. SingleFile is relying on this API https://developer.mozilla.org/docs/Mozilla/Add-ons/WebExtensions/API/downloads/download to download files. This API does not take into account the global option `Always ask you where to save files`. However, I also decided to disable `open the "Save as" dialog to confirm the file name` so it is an intentional design. Finally, for some technichal reasons, SingleFile can respect the global option if the setting `Misc > save pages in background` is disabled.

**Comment by zwn** [comment]
When I disable `Misc > save pages in background` I get an additional prompt for the name of the file, then I get the dialog to select the directory (regardless of what is set in the global Firefox options for downloads).

When reading the API page https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/downloads/download it seems that not providing `saveas` should provide the behavior I was initially expecting.

Anyway, thanks for the extension and links to the options I was not aware of. With them I am able to get what I wanted so I am fine.

**Comment by gildas-lormeau** [comment]
That's because I implemented a fallback "Save as" prompt for old versions of Firefox mobile. So when `Misc > save pages in background` is disabled, you also need to disable `open the "Save as" dialog to confirm the file name`.

I did not notice that info in the doc... Thank you very much for the notifying me. This does not seem to be the same in Chrome (https://developer.chrome.com/extensions/downloads#method-download) but I'll try to see if I can improve things on Firefox.
`
