### ISSUE TITLE
Best Options for CLI

### ISSUE THREAD

**Issue by yohfdo** [gildas-lormeau/SingleFile#490]
Hi, 

Thanks for this option both on Firefox and now with the CLI interface as well! I do have one question though as it seems some pages appear differently from the add-on and the CLI. For example, https://github.com/gildas-lormeau/SingleFile appears differently through the Firefox add-on vs the CLI. 

For the CLI, I used the following command:
`~/Downloads/SingleFile-master/cli/single-file https://github.com/gildas-lormeau/SingleFile --back-end=webdriver-gecko --browser-wait-until="domcontentloaded" --remove-imports=false --remove-scripts=false`

This is the result of the CLI
![image](https://user-images.githubusercontent.com/39078084/93172037-75ea3280-f76d-11ea-92bc-e4e83584b601.png)

Result of the Add-on
![image](https://user-images.githubusercontent.com/39078084/93172101-91553d80-f76d-11ea-87ac-a278f56dcdb5.png)

**Comment by gildas-lormeau** [comment]
Right now, I cannot test this issue because it seems webdriver does not work with the current Firefox nightly. On my machine, the browser is launched but the URL is not opened.

**Comment by gildas-lormeau** [comment]
So, I was able to do some tests with Firefox dev edition. The page cannot be saved with WebDriver and Firefox because of the CSP (https://developer.mozilla.org/docs/Web/HTTP/CSP) of the page. I tried to override the user preference in order to disable it but that did not work. Unfortunately, I cannot fix this issue and I may remove the support for Firefox via WebDriver in SingleFile CLI.

**Comment by gildas-lormeau** [comment]
Note that I added the support of Puppeteer on Firefox. However, I see exactly the same issue and it looks like it's a bug in Firefox. More info here: https://github.com/puppeteer/puppeteer/issues/5755.

**Comment by yohfdo** [comment]
Just checked this with the chrome/chromium webdriver and this issue doesn't exist - the web page is downloaded normally.

**Comment by gildas-lormeau** [comment]
@yohfdo I confirm this will fork fine with Chrome because it's possible to bypass the CSP in this browser. 
Note that I also added the support of [playwright](https://github.com/microsoft/playwright). It's still a work in progress but it allows saving the page with Firefox properly.
If you want to test it, update the code of SingleFile, run `npm install playwright` in the SingleFile folder and use the flag `--back-end=playwright-firefox`.

**Comment by gildas-lormeau** [comment]
I'm closing this issue since it's a bug in Firefox (see https://bugzilla.mozilla.org/show_bug.cgi?id=1549481). Once this bug will be fixed, it should work as expected in SingleFile.
