### ISSUE TITLE
cannont save page

### ISSUE THREAD

**Issue by NOSEBAG** [gildas-lormeau/SingleFile#512]
Hi Support

Never had a problem saving pages.

But now I cannot save either of these links
https://www.extendoffice.com/product/office-tab.html
https://www.extendoffice.com/forum/office-tab/780-office-tab-14-00-%E2%80%93-release-notes.html

Eith FF or Chrome ;-(
Any ideas?

Is it a bug?

Hope you can advise / fix

Many thanks
Ian H

**Comment by gildas-lormeau** [comment]
Thank you for having reported this issue. I was able to reproduce it and fix it. It was due to an invalid font declaration in CSS which contains no `src`. It will be fixed in the next version I'll publish. Meanwhile you can circumvent it by disabling the setting `Fonts > remove alternative fonts`. I recommend you to enable again this setting once these pages saved because it helps a lot to reduce the size of the files produced by SingleFile.

**Comment by gildas-lormeau** [comment]
The version 1.18.16 that fixes this issue is available for download in the store of Chrome.

**Comment by NOSEBAG** [comment]
Many thanks Gildas!
Great to see a fix has been issued so fast

Best regards
Nosebag
