### ISSUE TITLE
Latest version not working on waterfox classic 

### ISSUE THREAD

**Issue by RussetHelm** [gildas-lormeau/SingleFile#540]
Wanted to let you know that there seems to be a problem with the latest Version 1.18.26 on Waterfox Classic.  Clicking the button to save the file always produces the error message "this page cannot be saved with SingleFile."  I tried to install SingleFileZ to achieve similar functionality, and had the same problem, with the minor variation that the error message said "this page cannot be saved with SingleFileZ."

Since I noticed that you had just updated the addon, I tried installing the old Version 1.18.25 and it works fine.  I then tried to use SingleFileZ but it still didn't work.  I found the older version of that as well, and again, it works fine.  I am afraid that you must have made a change with both addons in the latest version that breaks their functionality in Waterfox Classic, but hopefully the knowledge that the problematic change is in both addons will help you to sort out the problem.

**Comment by gildas-lormeau** [comment]
Thank you for reporting this issue. Unfortunately, I cannot reproduce it with the version `2020.09` and `2020.10` and the latest versions of SingleFile/SingleFileZ. 

This message is displayed when SingleFile detects that the content script it's trying to execute into the page cannot run. This is typically what happens on internal pages (e.g. `about:config`) or pages from some domains like `https://addons.mozilla.org`.

Moreover the change in the version 1.18.26 is quite minor and not related at all with this code in SingleFile. I'm afraid the issue is due to another reason I cannot identify yet.

**Comment by gildas-lormeau** [comment]
@RussetHelm any news?

**Comment by womonix** [comment]
Bonjour Gildas,
i can confirm that there is a problem with SingleFile 1.18.30  on Waterfox Classic  2020.10 on all websites.
No problem with  SingleFile 1.18.26 on Firefox 82.0.2, both under Manjaro Linux
Eberhard

**Comment by gildas-lormeau** [comment]
@womonix Thank you for the additional info. Actually, I think I've found the cause of the issue. This would be due to the fact that I've enabled `dom.webcomponents.enabled` in `about:config`. SingleFile is using web components to isolate the UI elements it injects in the page from the page itself. This fixes for example this bug https://github.com/gildas-lormeau/SingleFileZ/issues/73. I've also seen similar rendering issues in the "logs panel" of SingleFile at the bottom left of the page.

**Comment by gildas-lormeau** [comment]
I pushed a new version which circumvents this issue. SingleFile will work in Waterfox Classic out-of-the-box but the UI elements (progress bar, logs, infobar) won't be displayed unless you enable `dom.webcomponents.enabled` in `about:config`.

**Comment by gildas-lormeau** [comment]
The infobar issue will be fixed in the version 1.18.33 (without needing to set `dom.webcomponents.enabled` to `true`).
