### ISSUE TITLE
Replace paragraphs with spaces

### ISSUE THREAD

**Issue by gerroon** [gildas-lormeau/SingleFile#566]
**Is your feature request related to a problem? Please describe.**

The indents in html files do not look good when copy pasted to regular text documents since they are regular paragraphs. I am wondering if it is possible for this extension to have an option for replacing those indents with spaces so that the text can be reproduced in regular text files/

I realize this is not a direct responsibility of this extension but it processes the whole page so maybe this can be a good option to offfer.

**Comment by gildas-lormeau** [comment]
Could you please provide a URL to show the issue, if possible?

**Comment by gerroon** [comment]
I cant remember a URL atm but I made a sample html file for you.

Open it in a browser and copy and paste into a text editor, you will see the formattting is not preserved.

**Comment by gildas-lormeau** [comment]
Thank you for the test page. Actually, the formatting is not preserved because it's done in CSS and you're just copying the text. I was thinking the issue was for example related to tab vs space characters instead. I cannot re-create indents by interpreting margins because it would be too complicated to implement, I guess. Moreover, by supposing it's can be done "easily", that would also lead to false positives since margins are not necessarily used to indent text.

**Comment by gerroon** [comment]
Hi

I do not know alot about html and css, so sorry for misrepresenting the issue. I assumed it was tab but it seems more complicated than that. Thanks for looking into it.

**Comment by gildas-lormeau** [comment]
You're welcome. I'm closing this issue because I don't think I would be able to implement something that would work.
