### ISSUE TITLE
Indicate that a page has already been saved

### ISSUE THREAD

**Issue by Lasonneil** [gildas-lormeau/SingleFile#570]
比如某一个网页被我下载下来了，但是当下次我又进入相同的网站，可不可以显示此网页已经被我下载，并且显示上一次下载是何时

**Comment by gildas-lormeau** [comment]
I don't speak Chinese so I'm replying in English and including the translated response below (I used deepl.com).

---

That's a good question! This is complicated to implement because SingleFile cannot reliably know whether a page has already been saved or not.
However, this functionality could perhaps exist in an application that relies on SingleFile. I am thinking in particular of [Zotero](https://github.com/zotero/zotero) which could rely on its database to know whether a page is saved or not. Unfortunately, this functionality is also missing. You can find more info here: https://github.com/zotero/zotero/issues/1007.

---

我不会说中文，所以我用英文回复，包括下面的翻译回复。

这是一个很好的问题！这个问题很复杂，因为SingleFile不能可靠地知道一个页面是否已经被保存。实现这个功能很复杂，因为SingleFile无法可靠地知道一个页面是否已经被保存。
然而，这个功能或许可以存在于依赖 SingleFile 的应用程序中。我特别想到了 [Zotero](https://github.com/zotero/zotero)，它可以依靠它的数据库来知道一个页面是否被保存。不幸的是，这个功能也是缺失的。你可以在这里找到更多信息：https://github.com/zotero/zotero/issues/1007。

**Comment by gildas-lormeau** [comment]
I forgot to mention that [ArchiveBox](https://github.com/ArchiveBox/ArchiveBox) also uses SingleFile but as far as I know, no extensions exist yet.
---
我忘了说，[ArchiveBox](https://github.com/ArchiveBox/ArchiveBox)也使用SingleFile，但据我所知，还没有任何扩展存在。

**Comment by Lasonneil** [comment]
Appreciate  for your reply ^ ^, actually i have an idea ,singlefile could save the url in a local text file(which located in the singlefile's folder ),and then compare the site with the urls in the text file to find if  that site have been down loaded,  forgive my poor english and childish idea( a tiro in the program world ，thanks ^^)
btw, singlefile is really a good tool: ）

**Comment by gildas-lormeau** [comment]
This is an interesting idea. Unfortunately, it's technically impossible for an extension to read the content of a file from the filesystem.

**Comment by gildas-lormeau** [comment]
A poor's man solution could be to use bookmarks for this. You could enable `Bookmarks > save the page of a newly created bookmark` and disable `Bookmarks > link the new bookmark to the saved page`. Then, if you see the page is bookmarked it means you (probably) saved it.

**Comment by Lasonneil** [comment]
hahaha 😆 that's could be a good idea, appreciate for  your reply

**Comment by gildas-lormeau** [comment]
You're welcome :)

**Comment by user0022** [comment]
Hello! 
Thanks for the issue opened and the answers given, for I had also thought about this, which I found that could be useful or indispensable, especially for "bulk save" or auto-save. And I feel that an access to the list of saved pages could also permit many other features.
I trust in the developper's competence, but it's too hard for me to believe that an addon can't perform such an elementary task, to know the addresses of the pages it has itself saved!
(I use  Firefox.)


*
So I'd just like to try some other suggestions, well as I'm zero-level, excuse-me if ideas are too stupid! But who knows.
So the obstacle seems to be that an URLs list wouldn't be accessible to SF "locally" or "on the computer". So I just searched where a text could be accessible to an addon.

**In Firefox "itself"?**
Maybe totally wrong, but I had the idea that a place in the Firefox "body" (interface?) could be reachable by SF to write the URLs and to read them.
- In the content of an open tab?
 A "dummy" or "virtual" tab maybe, that could be invisible if possible.
 If the list is somehow displayed in a FF open page, like if it would be a web page, or the page of an addon options, then it is accessible?
- In a SF Menu item?
- In a "dummy" bookmarks folder?
 After reading the "bookmarks solution"  you gave Mr Lormeau, I feel that a problem would be that this way to do removes an existing feature. But could it be better then if keeping both? An option would be sthg like "Create a bookmark folder with saved pages URIs", but independant of other enabled bookmarks features if possible. And saving a tab would compare to this folder.
- With the local content open in a tab?
 As Firefox can display local folders and files, simply for instance with putting /home/myself/Downloads/ in URL bar. Maybe once URIs displayed there in FF itself, SF can read the URLs in the file of each URI or open the file among them which would content their list?
- Etc.

(The last 2 ones a bit too imaginative I think but I tell them anyway.)
- In the address bar of a tab?
 ("Virtual tab" too?)
 I think that an addon can read this place, as e. g. there are addons which prevent duplicate tabs, which is maybe done by reading the bar text (but maybe by another mean).
 So maybe instead of having there one URL, there could be a big list. I tested it by copying a 1Mo text in it and it took it. Same test with 5Mo was a bit too much for my old weak PC. 
 BUT even if possible, I already imagine conflicts with some Firefox functions, and with many addons that would use the address bar text. Maybe also an address bar could be isolated or reserved to SF but well.
- In the SF icon?
 Maybe like a text hidden in an image, made invisible but nevertheless accessible.


**In a session manager or blacklist addon way?**
Addons that save browsing sessions, if I understand, they manage to save URLs, but then not somewhere "that can't be read", but somewhere that can be (like MySessions, which choose to make it in Bookmarks but others didn't).
But maybe also, displaying them is a thing, but comparing them and triggering an action after that is something else. Maybe addons that can cleanup Bookmarks by e.g. removing duplicates can help?
A bit the same thing with the blacklist addons.
And probably other kinds of addons which can save and read URLs. So it it possible to copy their functionning?


**Remotely?**
Could it be done in a remote place?
- When saving pages, SF would send their URLs in "a distant server" or "a web service" or "the cloud" (I don't know what and what name). And before saving a page or not, SF would compare the URL to this list.
- If SF can't see what is on "local disk", can it be circumvented with SF communicating with a remote software, which him can see this, and can afterwards send local files openings actions?


(Solution a bit different. The URLs aren't saved somewhere else now.)

**With an additional software?**
Maybe an optionnal additionnal script or application or software (a thing like that...), that should be downloaded separately, could read the saved pages, and communicate with SF bypassing Firefox?
In this case I have the hypothesis (??) that despite an addon can not read the user's "local content", an installed software (which can be considered as a "local content"?) can do the inverse, that is talk to the addon. 
If SF is still prevented to communicate with this software because it is installed "locally", maybe the communication between them can be done remotely? (Web etc.). It could avoid to store lists like in the previous proposal, the software would just send a signal "already saved".
I just saw the existence of the "Companion" program. I didn't try it yet, but could it be the "external software" I thought of?



*
Conclusion.
Conclusion is......... suspense....
0! Nothing works thank you. Go to bed now. :/
