### ISSUE TITLE
CLI: Infinitely opens blank pages, causing high CPU usage

### ISSUE THREAD

**Issue by Unknow0059** [gildas-lormeau/SingleFile#579]
**Describe the bug**
Title.

**To Reproduce**
1. Open CMD
2. Enter `single-file --crawl-links --crawl-replace-urls --crawl-sync-session=yolo.txt --error-file=error.log --browser-debug https://github.com/TDToolbox/BTD-Docs/tree/master/Unity%20Engine/Btd6/NKHook6`
3. Observe

**Expected behavior**
Pages to be downloaded.

**Screenshots**
![image](https://user-images.githubusercontent.com/25656892/103250218-9a9b9c00-4951-11eb-83df-87c5bd16ef65.png)

**Environment**
 - OS: Windows 10 Pro 2004 10.0.19041.685 64-bit
 - Browser: Chrome
 - Single-File Version: 0.1.14

**Additional context**
I don't know if the URL shown in the screenshot is the one being opened over and over, but if you try to open it, it will lead to a GitHub 404 page.

**Comment by gildas-lormeau** [comment]
I did a quick test and was able to capture ~ 20 pages. I confirm this causes a high CPU usage. This is normal because the "--browser-debug" option opens a debugger in each tab. To avoid this, you can use `--browser-headless=false` instead. This will help to reduce the CPU usage. By default SingleFile uses all the logical cores of the CPU. You can configure the number of tabs used simultaneously with the option `--max-parallel-workers` (e.g. `--max-parallel-workers=2` to use 2 tabs).

I was not able to reproduce the "Infinitely opens blank pages" issue. On my end, I see that files are saved on the disk as expected. Note that I stopped the crawl after 20 pages because I would download the whole internet. 

The version 0.1.14 is a bit old. I would recommend you to update SingleFile and do the test again. Also, how many pages were you able to capture before the issue appeared? The 404 issue is a bit weird since the URL shown in the screenshot, i.e. https://github.com/TDToolbox/BTD-Docs/stargazers, is not a 404.

**Comment by Unknow0059** [comment]
> Note that I stopped the crawl after 20 pages because I would download the whole internet.

Why would the crawl download all pages by default?
In the description for the `--crawl-max-depth` and `--crawl-external-links-max-depth` commands, it says that they are 1 by default.
I assumed this would hold true even if the commands were omitted, but I guess not.
> Also, how many pages were you able to capture before the issue appeared?

Just one - the same page being given as the parameter.
> The 404 issue is a bit weird 

Ah... It really is not a 404 page. I copied the URL manually, so I must've mistyped.

I have now updated.

The pages were blank because the CPU usage was so high that I couldn't see them load before my computer became mostly unresponsive, at which point I closed the browser.

**Comment by gildas-lormeau** [comment]
> > Note that I stopped the crawl after 20 pages because I would download the whole internet.
> 
> Why would the crawl download all pages by default?
> In the description for the `--crawl-max-depth` and `--crawl-external-links-max-depth` commands, it says that they are 1 by default.
> I assumed this would hold true even if the commands were omitted, but I guess not.

You're right, I would not have crawled the whole internet because of the default values you mentioned.


> By the way, some feedback on `--help`: it is not clear that there must be a `=` between an option and its value (like `--crawl-max-depth=1`) in the Option syntax, as opposed to a space (like `--crawl-max-depth 1`).

You can actually use both syntax variants.
