### ISSUE TITLE
Problem with pass referer option

### ISSUE THREAD

**Issue by k12fm** [gildas-lormeau/SingleFile#580]
Problem when saving a page with the option "pass Referer header after a cross-origin request error", some images are not saved, and when testing the get request with the referer property in the header with the main url of the website, the image load.
I attach a zip with the saved page, a sample in mhtml format and the configuration used. The page saved with SingleFile does not show all the images in the list.

[Test files.zip](https://github.com/gildas-lormeau/SingleFile/files/5759504/Test.files.zip)

**Environment**
 - OS: Win10 Pro x64
 - Browser: Chrome
 - Version:1.18.60

**Comment by gildas-lormeau** [comment]
Thank you for having reported this issue. I was able to reproduce it, this problem is not related to the option `pass 'Referer' header after a cross-origin request error`. It's due to an invalid declaration in the CSS instead. The `<div>` with the empty image contains the attribute

`style="background-image: url('https://s4.imgmirror.club/images/20200822/5f408e48a81e8_5f408e4a42aed.jpg"` 

while it should be:

`style="background-image: url('https://s4.imgmirror.club/images/20200822/5f408e48a81e8_5f408e4a42aed.jpg')"` 

Because of this syntax error, SingleFile cannot replace the image URL.

**Comment by k12fm** [comment]
Thanks for the information, I will close the issue since it does not apply to the extension, sorry for opening the issue, I had not seen the malformed css code.
