### ISSUE TITLE
Page captured with Firefox not correctly rendered with Chrome

### ISSUE THREAD

**Issue by bansan85** [gildas-lormeau/SingleFile#588]
**Describe the bug**

Capturing a page with firefox is not correctly rendered with Chrome.
The same page captured with Chrome is correctly rendered with Chrome and Firefox.

**To Reproduce**
1. Open Firefox 84.0.1 (64 bits) and SingleFile 1.18.61
2. Go to https://wenku.baidu.com/view/2a68c769011ca300a6c39059.html
3. Scroll down a little.
4. Click on

![image](https://user-images.githubusercontent.com/9248729/103894754-a9234980-50ef-11eb-8620-6f6fd91c9f6e.png)

5. Scroll down to

![image](https://user-images.githubusercontent.com/9248729/103895041-0ddea400-50f0-11eb-81b8-537d14051dc2.png)

6. Capture the page.
7. Open it with Firefox.
8. Check that the schema is correctly rendered.
9. Open it with Chrome Version 87.0.4280.141 (Build officiel) (64 bits)
10. Check that the schema is NOT correctly rendered.

![image](https://user-images.githubusercontent.com/9248729/103895390-a2e19d00-50f0-11eb-8417-beaf83952b3f.png)

11. Open Chrome and SingleFile 1.18.61
12. Open https://wenku.baidu.com/view/2a68c769011ca300a6c39059.html
13. Click on the link "Show more"
14. Scroll down to schema to check the correct render
15. Capture the page
16. Open it with Chrome and check the schema is correctly rendered.
17. Open it with Firefex and check the schema is correctly rendered.

**Expected behavior**

Page captured with Firefox should be correctly rendered with Chrome

**Environment**
 - OS: Win10 Pro Version 20H2, 19042.685

**Captured example**

Firefox (bad) : 
[Firefox_bad.zip](https://github.com/gildas-lormeau/SingleFile/files/5781721/Firefox_bad.zip)

Chrome (good) :

[Chrome_good.zip](https://github.com/gildas-lormeau/SingleFile/files/5781727/Chrome_good.zip)

Thanks and good luck :)

**Comment by gildas-lormeau** [comment]
I confirm the issue. This problem is related to the fact that the CSS of the page changes depending on the browser used to view it.

When displayed in Firefox, the image has the following property `-moz-transform: scale(0.5757643157894736, 0.581867940552017)`. But when displayed in Chrome, the property is replaced with `-webkit-transform: scale(0.5757643157894736, 0.581867940552017)`. Firefox can interpret `-webkit-transform` but Chrome refuses to interpret `-moz-transform`. That's why this issue does not exist when you save this page in Chrome and display it in Firefox.

The property the website should use is [`transform`](https://developer.mozilla.org/en-US/docs/Web/CSS/transform).`-moz-transform` and `-webkit-transform` are deprecated for years. Hopefully, this kind of browser incompatibilities will disappear in the future (it was much worse 15 years ago). There's nothing SingleFile can reasonably do to fix this.

**Comment by bansan85** [comment]
Sure, I understand. Thanks a lot for the review. I let you close this issue.

**Comment by gildas-lormeau** [comment]
You're welcome :)
