### ISSUE TITLE
Formatting problems

### ISSUE THREAD

**Issue by Jens116** [gildas-lormeau/SingleFile#59]
Hello Gildas, I found a formatting problem in your tool. If I create the single html5-File on a PC with high resolution graphics and transfer it to a PC with little lower resolution, the images are not formatted correctly. The images appear too large and they overlapp the text that flows round them. It would be nice if you find a solution for this problem. Best wishes Jens.

**Comment by gildas-lormeau** [comment]
Hi Jens, could you attach an example of file where this issue is present?

**Comment by Jens116** [comment]
Hi Gildas, I made the test with the following Amazon website:
https://www.amazon.de/Bosch-TWK1201N-Wasserkocher-1-7L/dp/B0009WWDGS/ref=sr_1_1?ie=UTF8&qid=1535564227&sr=8-1&keywords=bosch+twk1201n+wasserkocher
. Please save this page with SingleFile under Firefox (Windows 10), transfer
the file to a PC with lower graphic resolution and then load the file with
Firefox. I also tested the HTML5-File with Chrome under Android. In both cases
you will see, that the main image overlapps the text in some parts.


Am 29.08.2018 um 14:14 schrieb Gildas Lormeau <notifications@github.com>:
Hi Jens, could you attach an example of file where this issue is present?

**Comment by gildas-lormeau** [comment]
Hi Jens, Thanks for the example. Unfortunately, I don't think it's technically possible to automatically apply changes to such complicated pages in order to display them correctly on screens with lower definitions. For example, the reader mode on Firefox is not really able to display this page correctly.

If Amazon implemented their website correctly (i.e. made compatible with mobile devices) like the majority of web sites, the problem would not occur. 

If you're using Chrome, you can however circumvent this issue by installing an extension to display pages in reader mode like this one for example: https://chrome.google.com/webstore/detail/just-read/dgmanlpmmkibanfdgjocnabmcaclkmod/related?hl=en. If you activate the reader mode before saving the page with SingleFile then you'll get a page that is more adapted to devices with smaller screens.

**Comment by Jens116** [comment]
Hi Gildas, may be the Amazon page is too complicate. Next days I will give
your tip with the reader extensions a try. Thanks a lot for your help - and of
course for your extension. 


Am 30.08.2018 um 18:51 schrieb Gildas Lormeau <notifications@github.com>:
Hi Jens, Thanks for the example. Unfortunately, I don't think it's technically
possible to automatically apply changes to such complicated pages in order to
display them correctly on screens with lower definitions. For example, the
reader mode on Firefox is not really able to display this page correctly.
If Amazon implemented their website correctly (i.e. made compatible with
mobile devices) like the majority of web sites, the problem would not occur.
If you're using Chrome, you can however circumvent this issue by installing an
extension to display pages in reader mode like this one for example:
https://chrome.google.com/webstore/detail/just-read/dgmanlpmmkibanfdgjocnabmcaclkmod/related?hl=en.
If you activate the reader mode before saving the page with SingleFile then
you'll get a page that is more adapted to devices with smaller screens.

**Comment by gildas-lormeau** [comment]
You're welcome!
