### ISSUE TITLE
option to save as bare bone html with smallest size possible

### ISSUE THREAD

**Issue by avidh** [gildas-lormeau/SingleFile#597]
Hi,

First of all, thank you for this amazing extension.  This is the closest extension with features that I was looking for.
I basically save 10 to 20 tabs in Chrome then open them once a week then need to save all tabs as separate files so I can parse and process those files for my own needs.
I don't really need <meta>, <style>, <script>, and even images since I only care about the html body content.
But the <style> and converted images make the file very big.. close to 1 mb per file.
Could you please add an option to strip <meta>, <style>, <script> and even images so that files are smaller?

Thank you!

**Comment by GoblinLegislator** [comment]
I would like this option too. Unfortunately this can't be performed by browser's save as html, because it only loads original page, the one as it appears before pressing buttons like "load more". However using Firefox's save as txt does work for that purpose, it really saves text that appeared even after pressing "load more" button. Perfect example is IMDb where it does not have feature to back up user's reviews, but has feature to backup user ratings as csv. So the most efficient way I found to load all reviews is to press "load more" button until all reviews are loaded, then save page as pure html. Even if ugly it would be fast, and no text would be hidden by css. Also I can use uMatrix or uBlock origin or disable loading images by browser to speed up browsing of such list. Maybe add it into advanced settings somewhere because few users would need this. Example page: https://www.imdb.com/user/ur1592694/comments
Other users reporting no backup feature of imdb user reviews: https://community-imdb.sprinklr.com/conversations/imdbcom/is-there-a-way-to-export-all-of-your-imdb-movie-reviews-to-a-file/5f9ae70049d3ca3d56baa2e0
But this would only be efficient if you can prevent extension from downloading all other files (css, images).
Downloading them then removing them would be inefficient.

**Comment by gildas-lormeau** [comment]
We already discussed about this issue almost two years ago, see https://github.com/gildas-lormeau/SingleFile/issues/223. My point of view did not really change meanwhile.

However, I implemented the "format the page" feature  in the annotation editor. Maybe that would help?

See ![image](https://user-images.githubusercontent.com/396787/106401329-cd8af100-6423-11eb-94b1-1a94efa96cad.png) button

**Comment by gildas-lormeau** [comment]
I'm closing the issue for the same reason than https://github.com/gildas-lormeau/SingleFile/issues/223.
