### ISSUE TITLE
CLI renders page too quickly and dumps incomplete result

### ISSUE THREAD

**Issue by komodovaran** [gildas-lormeau/SingleFile#612]
I'm writing results to apps built in https://www.streamlit.io/. SingleFile is an amazing way to grab the entire page for later. However, when using the docker CLI, it renders the page too quickly, so if the entire page takes e.g. 30 seconds to load on first run, the CLI will run for ~5 second, and only grab whatever content was loaded after that amount of time. By design, Streamlit apps will not tell the browser that they're in a loading state.

The GUI Chrome browser extension works fine because I can just manually wait for the page to finish loading.

Is there an option to force the CLI to wait for X seconds, before grabbing the output? It doesn't seem like any of the `--browser-wait-until` parameters work; it still thinks the page is loaded when it isn't.

**Comment by gildas-lormeau** [comment]
I did not really realize, I guess, that this option was missing. I added it in the version I just published. The option is `--browser-wait-delay`, it accepts a delay in ms. I would be curious to know an example of URL that shows this issue though, because I might be able to fix it without needing to use this option.

**Comment by komodovaran** [comment]
For example, this app: http://ezancestry.herokuapp.com/

If you click "UMAP" it will start rendering for a long time, but this is all handled by the app without notifying the browser.
