### ISSUE TITLE
Certain elements saved but not whole page

### ISSUE THREAD

**Issue by tech189** [gildas-lormeau/SingleFile#618]
**Describe the bug**
I am trying to save this page: http://www.salimbeti.com/micenei/chariots.htm
But if I save it, the page immediately refreshes before any of the steps to save can complete. If I try to save just the `<center>` tag of the table (where the content starts, from 'The chariot, ...') it works, just not the whole page. It looks like a really old page with no CSS so maybe something to do with some IE formatting quirk? I tried doing it in a private window with no other extensions and restarted the browser but no luck.

**To Reproduce**
1. Go to http://www.salimbeti.com/micenei/chariots.htm
2. Click on the SingleFile icon to start saving
3. The 'Deferred images...' popup appears and immediately disappears
4. The page refreshes
5. Page is not saved :(

**Environment**
Tested on Windows & macOS in Firefox and Edge
 - OS: Windows 10 20H2, macOS Big Sur 11.2.1
 - Browser: Firefox 85.0.2, Edge 88.0.705.74

**Comment by gildas-lormeau** [comment]
I confirm I can reproduce the issue. I need to debug the JS code to see what's wrong. Meanwhile, a way to circumvent easily this issue is to scroll to the bottom of the page and save it. This will prevent the code to load deferred images from running (since they're already loaded).

**Comment by gildas-lormeau** [comment]
So, I found the cause of the issue. This is due to the attribute `onresize="self.location.reload()"` on the `<body>` tag. When SingleFile tries to load the deferred images, it emulates a large screen to trigger the scripts that load these images. Unfortunately, on this particular website, if the screen is resized then the page is automatically reloaded (because of the `onresize` HTML attribute) and I don't know why the author decided to code such a behavior. I'm not sure I will find a way to prevent the page from reloading though.

**Comment by tech189** [comment]
Wow, I wonder why that is coded there... Thank you for the work-around it works perfectly!

**Comment by gildas-lormeau** [comment]
You're welcome!
