### ISSUE TITLE
Suggestion - Include original link

### ISSUE THREAD

**Issue by yohfdo** [gildas-lormeau/SingleFile#65]
Hi, 

Thanks for this extension! Its really useful!

Was wondering if there was a way to save the original URL in the filename? Or include it somehow in the file? 

Not sure if this is already included and I'm not looking in the right place.

**Comment by gildas-lormeau** [comment]
Hi,

It's not really possible to store the original URL in the filename because some Operating Systems like Windows are quite restrictive regarding the characters that are allowed in a filename. It's already included in the saved file though. For example, if I save this page and open it in a text editor, it contains the following header.
```
<!DOCTYPE html> <html lang=en><!--
 Archive processed by SingleFile
 url: https://github.com/gildas-lormeau/SingleFile/issues/65 
 saved date: Thu Sep 13 2018 11:30:54 GMT+0200
--><meta charset=utf-8>
```
You can also go to the original URL through the infobar when viewing an archive by clicking on the button at the right of the saved date. I plan to make it visible in the infobar somehow in a near future.

**Comment by yohfdo** [comment]
Oh wow! That's incredible! My apologies, I never noticed the little infobar/ info button. I think just having that link there is quite adequate, but if you could include it in the infobar then its one less click :)

But otherwise its perfect! Thanks again!

**Comment by gildas-lormeau** [comment]
No problem ;)
