### ISSUE TITLE
Companion save location?

### ISSUE THREAD

**Issue by element4l** [gildas-lormeau/SingleFile#654]
Hi there, I'm trying to get SingleFile to silently save pages as I browse. It seems without the companion, it will always bring up the download bar on my browser, cluttering my workspace as I browse. I tried setting up the companion, and got everything installed correctly (according to the instructions) and enabled the companion in the extension options, but nothing happens when I browse. There's nothing new in the downloads folder, there's nothing new in the SingleFile companion folder, and adding a "savePath": C:\Users\username\Downloads\History to the options.json doesn't do anything. I've tried with and without quotes, I've made sure it's an existing folder. How do I get this to work? I'm using Edge.

**Comment by gildas-lormeau** [comment]
So it's you! I knew someone was probably using the companion. There's been a long time I did not work on it to be honest, I'll some tests this weekend to see if it still works, and if there's something wrong with Edge in particular.

**Comment by gildas-lormeau** [comment]
I just pushed a fix in the companion project to add the support SingleFile in Edge. 

By default, the companion will try to process pages with Chrome though. If you want that the companion uses Edge instead, you have to update the `options.json` file in order to specify where the executable can be found. For this, you have to specify the value of the `browserExecutablePath` property, e.g. `"browserExecutablePath": "C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe"`.
