### ISSUE TITLE
various popups: advice needed

### ISSUE THREAD

**Issue by WellRedPandit** [gildas-lormeau/SingleFile#695]
Hi Gildas - i've been using your extension more and more. thank you again for creating it!

as i'm sure you know some media sites display popups that blur the page and require a user action (clicking a close button or typing the escape key) to reveal the underlying content. some popups do not respond to keys and demand a mouse click. i've been relying on post-processing (removing html elements from the file that SingleFile saves) but that doesn't work for sites that do not even send a request back to the server to get full content util a user dismisses the popup. so removing html elements in a saved file does nothing to reveal content that was not there in the first place :)

what would you recommend the right way be to tell SingleFile to click a button and "press" a key?

i can write conditional logic depending on a site url, no problem; and i sort of know :) that SingleFile can run a script (after a specified delay, right?) but i'm not a front-end developer so all this business of clicking and pressing escapes me :)

any advice you could give would be of course greatly appreciated!! thank you!

**Comment by gildas-lormeau** [comment]
The best way to achieve this is indeed to write a user script (see [here](https://github.com/gildas-lormeau/SingleFile/wiki/How-to-execute-a-user-script-before-a-page-is-saved)). The script is run just before the page is processed by SingleFile. This allows you for example to cleanup the page before saving it. 

I guess a good option for you would be to use a library that would help you to write scripts with a simple syntax. The problem is I don't know what to recommend. Maybe jQuery could help. It offers simple function to trigger mouse and keyboard events on DOM elements.

**Comment by WellRedPandit** [comment]
Thank you so much for your advice! jQuery is just as good as any other library i've never mastered :) I'll start there.
