### ISSUE TITLE
Get hexadecimal string for filename

### ISSUE THREAD

**Issue by arnie2031** [gildas-lormeau/SingleFile#729]
When I use the extension "Malwarebytes Browser Guard" with Windows 10 and the Google Chrome browser, SingleFile produces a hexadecimal string (with some dashes) for the file name.
Here is a Github file name with and without Malwarebytes Browser Guard:
95e4fcfb-7cfb-43aa-95c4-d89f1257f67c.htm
Issues · gildas-lormeau_SingleFile · GitHub (2021-07-28 6_06_10 PM).html

**To Reproduce**
1. Install and enable the Malwarebytes Browser Guard extension
2. Download webpage using the SingleFile extension
3. See error

**Expected behavior**
Download file with alphanumeric name and date-time stamp.

**Environment**
 - OS: Windows 10 Home 64 bit, Version 21H1, OS build 19043.1110
 - Browser: Google Chrome
 - Version: 92.0.4515.107 (Official Build) (64-bit)

**Comment by gildas-lormeau** [comment]
Unfortunately, this is a bug in Chrome, see https://bugs.chromium.org/p/chromium/issues/detail?id=892133 for more information. Also, this issue is closed as "Won't Fix". I have informed @DotProto, the developer advocate for Chrome extensions, of this issue on twitter (see https://twitter.com/check_ca/status/1413136372617994246). Hopefully something can be done about it.

**Comment by gildas-lormeau** [comment]
I'm closing the issue because it's already documented in the [know issues](https://github.com/gildas-lormeau/SingleFile#known-issues).

**Comment by gildas-lormeau** [comment]
Moreover, I'm pretty sure Google will never fix this bug and MV3 will end the job.
