### ISSUE TITLE
Images ignored when using cli on local files

### ISSUE THREAD

**Issue by zuhairmahd** [gildas-lormeau/SingleFile#744]
**Describe the bug**
Whenever running the commandline utility on a local file HTML file that references images stored on the file system, the images are ignored.
**To Reproduce**
1. Create an HTML file that references an image, either by saving it from a site or by converting a Word file.  Make sure you have images in the file.
2. Run the commandline utility as such: single-file file://path-to-local-file-and-filename.  You can also use a the --urls-file=filename option, as long as the files referenced in the .txt file are on the local FS in the format file://path-to-file-and-file-name
3. The conversion will take place, however, when you open the resulting file, the images will show as thumbnails, and looking at the source, the images are not binary encoded.
4. Now repeat the process, this time using the add-on in Chrome, making sure to enable access to the file system in the add-on options.  You will note that the conversion works fine and the images show up in the target file and are binary encoded.

**Expected behavior**
I would expect that the behaviour you see in the add-on is consistant with what you see in the commandline utility
**Screenshots**

**Environment**
 - OS: [e.g. Win10 Pro, Ubuntu 18.04.1, Android 7.1.2] Win10 Pro build 21H1
 - Browser: [e.g. Chrome, Firefox] Chrome 
 - Version: [e.g. 64] 92 (latest stable)

**Additional context**

**Comment by gildas-lormeau** [comment]
I confirm I can reproduce the issue. I might be wrong but if I remember correctly, passing the switch `--allow-file-access-from-files` to `chrome` (e.g. passing ` --browser-args="[\"--allow-file-access-from-files\"]"` to `single-file`) helped to this issue in the past. Unfortunately, it does not work. I think the simplest way to circumvent this issue is to run an HTTP server to process pages in HTTP. 
Depending on what you have already installed on your machine, you can easily run a HTTP server from the command line, see https://gist.github.com/willurd/5720255 for example.

**Comment by zuhairmahd** [comment]
Hi @gildas-lormeau .  Thanks for getting back to me.  That is exactly what I did, and it seems to take care of it.

Thanks,
Zuhair.
