### ISSUE TITLE
WebGL based canvas are filled with [0, 0, 0, 255]

### ISSUE THREAD

**Issue by dezmou** [gildas-lormeau/SingleFile#759]
**Describe the bug**
WebGL based canvas are full black on single file page.

**To Reproduce**
Create a single file page on a page featuring a simple webGL drawing 

**Expected behavior**
The simple webGL drawing appear on the single file page

**Comment by gildas-lormeau** [comment]
I confirm the bug. I'll try to fix it.

**Comment by gildas-lormeau** [comment]
This answer on SO https://stackoverflow.com/questions/7156971/webgl-readpixels-is-always-returning-0-0-0-0#answer-44534528 and this article https://webglfundamentals.org/webgl/lessons/webgl-tips.html make me think that it's in fact impossible to implement because SingleFile cannot know precisely when the rendering is done. I might be wrong though. 

The test I did is the following one:
1. Open https://webglsamples.org/aquarium/aquarium.html
2. Run the code below in the developer console
```js
const context = canvas.getContext("webgl", { preserveDrawingBuffer: true });
const pixels = new Uint8Array(canvas.width * canvas.height * 4);
context.readPixels(0, 0, canvas.width, canvas.height, context.RGBA, context.UNSIGNED_BYTE, pixels);
console.log(pixels);
```
It shows that the `pixels` array is only containing black pixels. Omitting the option `{ preserveDrawingBuffer: true }` gives the same result.

**Comment by gildas-lormeau** [comment]
I'm closing this issue because it cannot be fixed AFAIK. WebGL experts are welcome to contradict me though.

**Comment by akohlsmith** [comment]
Is this also the issue why the "mini demos" on the page https://nmattia.com/posts/2025-05-07-airpods-hearing-test-animation/ do not show up, although the controls for the mini demos are present on the saved page?
