### ISSUE TITLE
SingleFile slows down on outlook.office.com, when previewing PDF attachments

### ISSUE THREAD

**Issue by Fraxlin** [gildas-lormeau/SingleFile#783]
**Describe the bug**
After installing SingleFile, previewing PDF attachments on https://outlook.office.com/ becomes lagging and less responsive. Firefox gives the following warning:
`"SingleFile" is slowing down Firefox. To speed up your browser, stop that extension. Learn more at https://support.mozilla.org/en-US/kb/warning-unresponsive-script#w_other-causes`

After disabling SingleFile, the issue disappears. The lagging issue will re-appear if re-enabling SingleFile.

Throughout the whole process, the SingleFile button was never clicked.

**To Reproduce**
1. Open an email with a PDF attachment (preferably not too small)
2. Click on the right arrow next to the attachment and select preview
3. The website becomes lagging
4. The Firefox warning will appear
5. After a couple of seconds (depends on the type of PDF, could be 5-10-30 secs) everything returns to normal behavior

**Expected behavior**
Firefox should act normally, regardless if SingleFile is installed, activated or not.

**Environment**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 92.0
 - Latest version of SingleFile

**Comment by gildas-lormeau** [comment]
Thank you for the detailed report. I could not reproduce the issue because I don't use outlook but I guess it's similar to https://github.com/gildas-lormeau/SingleFile/issues/755. I optimized more the code which detects fonts that are loaded dynamically in the version 1.19.10 of SingleFile. Please let me know, once the version available on the store (hopefully in 24-48 hours) if it fixes the issue.

**Comment by Fraxlin** [comment]
Ok, SingleFile just updated to v1.19.10, and I don't have the issue anymore: everything is fast as it should be.
Thanks for the super quick fix :)

**Comment by gildas-lormeau** [comment]
You're welcome! :)
