### ISSUE TITLE
可否让用户自主选择仍然以带文件夹的双文件的旧形式来保存网页？

### ISSUE THREAD

**Issue by gemkeeper** [gildas-lormeau/SingleFile#838]
作者你好，我来自中国，很多中国人非常喜欢你研发的这个插件(你的技术和想法真的太厉害了！太让人佩服了！)，还有谷歌的Chrome64浏览器
 1其实，很多人仍然喜欢和习惯使用 手工-网页另存为 所保存下来的那种 带文件夹的传统形式的html文件，（就是所有的图片放在一个与网页html相同名称的文件夹里，的那种形式）
  ——因为文件夹里的图片 可以自由随意 浏览、批量复制、或者批量删除，
  ——而且，这种传统的 带文件夹的html格式双文档，很方便使用word进行编辑，网页里的图片在word里全部都可以正常显示，
   但是，用这个插件保存得到的 单文件html，用word编辑时，很多图片显示红色X号，不能显示。
。
  那么，本插件，以后，可否支持 让用户可以自主选择 仍然以 传统的带文件夹的形式 来保存网页（也就是双文件），而不是 强制只支持 生成 压缩包形式的 单一文件html？

**Environment**
 - OS: [Win7-64]
 - Browser: [Chrome64-V版本 96.0.4664.45（正式版本） （64 位）]
 - Version: [64]

**Comment by gildas-lormeau** [comment]
Thank you for your suggestion. The problem is that SingleFile is called SingleFile and saving the page as separate files would go against the name of the extension. Perhaps you would be more interested in [SingleFileZ](https://github.com/gildas-lormeau/SingleFileZ) which allows you to save a page as a zip file. This way you can extract it and modify it easily.

---
Translation with deepl.com:

谢谢你的建议。问题是，SingleFile被称为SingleFile，将页面保存为单独的文件会违背扩展名的名称。也许你会对[SingleFileZ](https://github.com/gildas-lormeau/SingleFileZ)更感兴趣，它允许你将一个页面保存为一个zip文件。这样你就可以轻松地解压和修改它。

**Comment by enjoywithme** [comment]
-Nice job - SingleFile and SingFileZ
