### ISSUE TITLE
有些网址无法下载图片

### ISSUE THREAD

**Issue by taswing** [gildas-lormeau/SingleFile#940]
**Describe the bug**
网页没有加载显示的图片，通过singlefile下载时，图片也无法显示

**To Reproduce**
1、访问https://mp.weixin.qq.com/s/E-BUVAr5LpqMJg5eQ7sD7g
2、直接点击singlefile插件，开始下载文件
3、点开下载完成的html文件，会发现里面未加载的图片无法显示，和常见问题里面描述不一致，能否优化下呢
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/96651291/166393267-11f958cd-493b-4198-bada-d4f31031bb6e.png">

**Expected behavior**
网页没有加载显示的图片，通过singlefile下载后，希望那些没有加载完成的图片也可以显示在html本地文件中

**Screenshots**
没有下载成功图片
<img width="1102" alt="image" src="https://user-images.githubusercontent.com/96651291/166393109-1d73e6c7-11e3-487b-bf9b-0df2002ef932.png">

**Environment**
 - OS: [e.g. macOS 12.3.1]
 - Browser: [e.g. Chrome ]
 - Version: [e.g. 101.0.4951.41]

**Additional context**

**Comment by gildas-lormeau** [comment]
The implementation of lazy loading on this site is somewhat buggy. 

Steps to reproduce the bug:

1. Open https://mp.weixin.qq.com/s/E-BUVAr5LpqMJg5eQ7sD7g
2. Zoom out **without scrolling**
3. Images which appear at the bottom of the page while zooming out are not displayed

Expected result: 

The images should be displayed.

This bug is the cause of the issue you described. So you'll have to manually scroll the page to save it until the developers of this website decide to implement something that works properly.

**Comment by gildas-lormeau** [comment]
Check the option `Images > load deferred images > dispatch 'scroll' event` to fix this issue. This option will be available in the version 1.21.4.

**Comment by gildas-lormeau** [comment]
I tried in the past to use the `data-src` attribute. The problem is that it is not standard and on some sites, it does contain a URL actually.
