### ISSUE TITLE
What the hell?

### ISSUE THREAD

**Issue by GildedHonour** [gildas-lormeau/SingleFile#967]
I don't undersand how it works if it'll always save a page without a) head tag b) closing body tag
This can be verified by looking at the source code of a saved page

**Comment by gildas-lormeau** [comment]
Let me cite the specification, see https://html.spec.whatwg.org/multipage/syntax.html#optional-tags

> A head element's start tag may be omitted if the element is empty, or if the first thing inside the head element is an element.

> A head element's end tag may be omitted if the head element is not immediately followed by ASCII whitespace or a comment.

> A body element's start tag may be omitted if the element is empty, or if the first thing inside the body element is not ASCII whitespace or a comment, except if the first thing inside the body element is a meta, link, script, style, or template element.

> A body element's end tag may be omitted if the body element is not immediately followed by a comment.

**Comment by GildedHonour** [comment]
Alright.
Is that for the sake of saving 15-20 characters?

**Comment by gildas-lormeau** [comment]
I'm sorry but what's the problem actually?

**Comment by GildedHonour** [comment]
Whenever I need to edit the source code, it gets confusing.
Some browsers, I guess, may not be able to recognize such html as valid too.
Some, or all, editors too because there'll be no matching tags for body or/and head.

**Comment by gildas-lormeau** [comment]
It would be a bug in these browsers, editors then. They should follow the specification especially given the fact that HTML5 standardized 14 years ago the parsing algorithm, see https://html.spec.whatwg.org/multipage/parsing.html.

However, I do not prevent users from disabling the option. In the past, the most recurrent complaint was that the pages produced by SingleFile were too heavy. That's why all the options that reduce this size and don't alter the document rendering are enabled by default.

**Comment by GildedHonour** [comment]
Ok. There're so many settings there. Which one disables this option?
