### ISSUE TITLE
Fails for some pages 

### ISSUE THREAD

**Issue by nicewaytodoit** [gildas-lormeau/SingleFile#982]
Just randomly tried this page and it failed multiple time or crashes the page:
https://pudding.cool/2022/06/aztec-gods/

Can work if I adjust options but then page does not look the same.

**Comment by gildas-lormeau** [comment]
I would say that you are not lucky. Unfortunately, this page has been poorly designed. It contains 137 occurrences of https://pudding.cool/2022/06/aztec-gods/assets/gods/sprite/gods.sprite.png. SingleFile has a mechanism in order to avoid embedding 137 times this image but it's disabled for images weighting more than 512 KB because Firefox refuses to display it otherwise. A simple way to circumvent this issue would be to use SingleFileZ.

**Comment by nicewaytodoit** [comment]
I would say differently, I am not unlucky, I am just lucky in finding bugs ;D
By the way I was using Chrome not Firefox.

**Comment by gildas-lormeau** [comment]
Well, youd a bug indeed, but in Firefox. SingleFile just tries to do its best to circumvent it.
