### ISSUE TITLE
Conflict between SingleFile v1.21.17 and extension "Link Status Redux" v3.16

### ISSUE THREAD

**Issue by 101Monkey** [gildas-lormeau/SingleFile#993]
**Describe the bug**
If the 2 extensions are enabled (even if it's only those two), and I click on "SingleFile/Annotate and save the page", the "Annotate" page opens, with the SingleFile controls on top, but the page content is blank (all white). This used to work perfectly before the last SingleFile update (v1.21.17 done today: 2022-07-06). If I use only SingleFIle, works as before (ie: perfectly).

**To Reproduce**

0. Select a dark theme in Firefox (edited)
1. Insure that SingleFile v1.21.17 AND "Link Status Redux" v3.16 are installed and enabled
2. Open a web page in Firefox Right-click on tab (problem occurs with every page I tried; the last one I checked was https://unherd.com/thepost/study-into-mrna/)
3. Right-click on the page's tab and click on "SingleFile / Annotate and save the page"
4. Once the "Annotate" page opens, what should be the web page content is all blank/white

**Expected behavior**
The web page content should show in the "Annotate" page.

**Screenshots**
This is what I get:
![image](https://user-images.githubusercontent.com/108835230/177639572-52437c91-6f01-4947-aeb7-c1576859d878.png)

**Environment**
 - OS: Win10 Pro x64
 - Browser: Firefox v102.0.1 (latest version)

**Additional context**
Thanks for a superb and essential extension.

**Comment by gildas-lormeau** [comment]
Thank you for the detailed report, I confirm I was able to reproduce the issue. From my point of view, this is a bug in "Link Status Redux". 

I did the test with https://example.com

As you can see in the developer tools at the right of the screenshot below, the content is present in the page but is not visible. Note that you can open the developer tools by pressing F12.

![image](https://user-images.githubusercontent.com/396787/177652862-043b0dd1-b142-4797-9181-df0ec10f6477.png)

It's actually hidden by the `<div id="e0fe7e79ef044e56993c0a0a6874baed" ...>...</div>` tag you can see in the screenshot. This tag is injected by "Link Status Redux" and hides all the content (you can see it by checking the "blue shadow" when hovering the tag in the developer tools). This tag should not be present in the page or should not hide its content.

So, I cannot really fix this issue on my end because it's specific to "Link Status Redux". If I circumvented it, then other people might come up with the same kind of problems and I would have to code specific workarounds for these conflicting extensions every time.

**Comment by 101Monkey** [comment]
Thanks for the quick reply. I did open the console and saw what you describe. I see that the tag is from "Link Status Redux". I can't really interpret the code well enough to be able to say that I "see" without the shadow of a doubt that it's causing everything to be blank. But I'll take your word for it (and it kind of make sense based on what I see in the tag's code).

I would add though that even if it looks like the "offensive" code is in "Link Status Redux", the problem wasn't manifesting before today's SingleFile update. So something that was done in SingleFile latest update "activated" the latent problem in "Link Status Redux". I'll try to forward the infos to it's author, hoping that he or she will agree with you that the "offensive" tag shouldn't be there. 

But meanwhile, since both extensions are very important to me, I'd like to be able to continue to use both. So, as far as you know, is there a way for me to go back to the previous version of SingleFile (it was working fine for my needs), until "Link Status Redux" is fixed (hoping it will be)? If it is doable, could you direct me toward a page or document showing the required steps to do it?

**Comment by gildas-lormeau** [comment]
I don't think a previous version of SingleFile will fix the issue. I did not make any changes in the annotation editor recently that could induce this bug AFAIK. I suspect a Firefox update might be the cause of the issue. You can install the latest versions of SingleFile from here: https://addons.mozilla.org/en-US/firefox/addon/single-file/versions/.

**Comment by 101Monkey** [comment]
Thanks for the quick reply and the link. You were right again: installing the previous version didn't fix the problem. And it is very likely that indeed a change in Firefox activated the problem (I didn't realize that Firefox was also updated today). So I hope something is doable on "Link Status Redux" side. If the "conflict" get resolved, do you want me to inform you? And if so, how should I go about it? By posting here?

**Comment by gildas-lormeau** [comment]
If you create an issue in the repository of Link Status Redux, feel free to add a link to this one. Thus, a backlink will appear here. You can also ping me by using @gildas-lormeau (anywhere on github) to keep me updated.

**Comment by gildas-lormeau** [comment]
@101Monkey I think you should add a comment here: https://github.com/jaatroko/link-status-redux/issues/41

I was able to circumvent the issue by using a light theme.

**Comment by 101Monkey** [comment]
I'll definitely add a comment there. And switching to a light theme also worked on my system. So that might be a workaround for now. I write "might" because now that I've used dark themes everywhere – i.e.: Windows, Firefox, etc. – it's hard to go back to light themes. I'll see if I can get used to that again. But anyway, thanks to have taken the time to test that. I appreciate it.

**Comment by gildas-lormeau** [comment]
You're welcome, I totally understand your point of view. I switched back to the dark theme immediately. The best workaround for me would be to use the previous version of Firefox.

**Comment by 101Monkey** [comment]
Thanks, again [sorry if I sound like a broken record :-)]. Indeed, rolling back to a previous version would definitely seem like a better option, but now, doing so requires creating a new Firefox profile. Apparently to avoid data corruption. There seems to be a way around it, but it's kind of risky (again: possible data corruption). I know I can make a profile backup... I'll see what I'll do.

**Comment by gildas-lormeau** [comment]
Seeing your bookmarks bar and because I really can't say it in English, I will tell you "bon courage" :)

I already suffered from a corrupted profile in Firefox in the past but I got out of it by deleting some of the files that were causing problems

**Comment by 101Monkey** [comment]
Ah, je me disais aussi que Lormeau "sonnait" français. Je suis Québécois. Salut cousin! Merci de l'encouragement, et pour tout le reste! :-) 

I'll go back to english so non-french speaking readers can follow. I've posted a comment in the Link Status Redux thread, with a link to this one, but I don't see any "backlink" here. Do you? Is it because I've posted in an already created thread instead of creating a new one?

**Comment by 101Monkey** [comment]
Just noticed that the "Link Status Redux" thread was flagged as "Closed". Maybe that's why there's no backlink?

**Comment by gildas-lormeau** [comment]
Salut cousin ! 

Indeed, the backlink issue is strange. I guess you're right :). Don't worry, it's a minor detail.

**Comment by 101Monkey** [comment]
Jaatroko, the author of "Link Status Redux" extension (LSR), has reopened the thread for which you posted a link earlier, and he added a new post in which he mentions that:

- there is a CSS workaround for the "whiteness" problem in relation to LSR, but that workaround doesn't work with/for SingleFile
- even though he didn't looked at SingleFile's code, his guess is that SingleFile does something (possibly modifying the color-scheme property?) to the page HTML/CSS which breaks the workaround.

Link to the thread: [https://github.com/jaatroko/link-status-redux/issues/41](url)

P.S.: Still no backlink even though the LSR thread is reopened.

**Comment by gildas-lormeau** [comment]
Thanks for the feedback, I did a short debugging session and added some comments in the thread. Unfortunately, I have currently no idea what could be causing this bug.

PS: your backlink is broken ;)

**Comment by jaatroko** [comment]
I think I have figured out the problem here. Thinking further about the color-scheme combination table on the [Link Status Redux issue page](https://github.com/jaatroko/link-status-redux/issues/41), as well as your comment there about white flicker on reload, it occured to me: how does SingleFile handle iframes? I mean, not knowing more about it, collapsing/flattening iframes into the parent document sounds like a non-trivial task at best, though that is besides the point here. What you have with LSR is an iframe that a) has restricted `moz-extension://` content and b) is hidden inside a shadow DOM. So when SingleFile copies the page to its own context, it is not allowed to load the iframe content. The empty content of the contentless iframe has a color-scheme default of "normal", resulting in a white screen with dark theme with the current LSR workaround. And because the iframe is hidden, SingleFile cannot even try to flatten or remove it.

While the semantics are debatable, there should be no practical difference between the four working color-scheme combinations, so what I'm going to do is change the LSR workaround to use the "light"-"normal" combination, which should resolve this issue as well as the white flicker on page reload (as long as Firefox does not change its behavior about this in the future).

**Comment by jaatroko** [comment]
Link Status Redux 3.17 is now available from AMO. Please confirm that it works for you.

**Comment by 101Monkey** [comment]
As I wrote on the LSR's thread, it does indeed solve the problem with SingleFile. Great work! Thanks to both of you!

**Comment by 101Monkey** [comment]
As I wrote on the LSR's thread, it does indeed solve the problem with SingleFile. Great work! Thanks to both of you!

**Comment by gildas-lormeau** [comment]
Thank you very much @jaatroko. I confirm it works perfectly now. I have read your explanations and I can clearly see that it took a lot of effort on your side to fix the bug. Congratulations!
